### ISSUE TITLE
Valiation fails when contained resource contains narrative Text property

### ISSUE THREAD

**Issue by petegee** [FirelyTeam/fhir-net-api#1002]
In the file 
https://github.com/FirelyTeam/fhir-net-api/blob/master-r4/src/Hl7.Fhir.Core/Model/DomainResource.cs

there is a validation which disallows a contained domain resource to have a Text element. From what ive read, this was explicitly not permitted in a previous version:
https://www.hl7.org/fhir/DSTU2/narrative.html
_"Note that contained Resources SHALL NOT have a narrative of their own."_

however this bit of text has been removed from the V4/latest spec
https://www.hl7.org/fhir/narrative.html
and it goes as far as saying it is permissible, but the current R4 .net library/nuget still does not allow it (see validation in file linked above).

So i propose the existing validation is now out of line with the R4 documentation, and is therefore a bug.

I will put together a PR with a proposed change.

**Comment by petegee** [comment]
PR @ https://github.com/FirelyTeam/fhir-net-api/pull/1006

**Comment by ewoutkramer** [comment]
Which has now been pulled. Will be part of the 1.3 release!

**Comment by petegee** [comment]
Cool thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
