### ISSUE TITLE
Model for FHIR R4

### ISSUE THREAD

**Issue by xiaojianbo73** [FirelyTeam/fhir-net-api#1008]
When to fully support FHIR R4?

I found:
- In R4, '$.subject' in imagingstudy would replace '$.patient' in STU3;
- In R4, there is no ProcedureRequest resource, but add ServiceRequest resource instead.

**Comment by mbaltus** [comment]
There's an R4 branch on this repository that contains those changes: https://github.com/FirelyTeam/fhir-net-api/tree/release-r4/1.2.1
Also you can use the Hl7.Fhir.R4 NuGet package in your VS project.
