### ISSUE TITLE
STU3 Encounter Won't Deserialize

### ISSUE THREAD

**Issue by PDRDaveF** [FirelyTeam/fhir-net-api#1009]
I'm currently passing a test JSON object to convert into an Encounter, instead I'm getting a raft of validation issues for the statusElement being NULL when I'm passing strings for the status.

The JSON is being passed in via Postman as raw, and I've tried with a content-type header of "application/fhir+json" as well "application/json"

JSON:
`{
  "resourceType": "Encounter",
  "id": "emerg",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Emergency visit that escalated into inpatient patient @example</div>"
  },
  "status": "in-progress",
  "statusHistory": [
    {
      "status": "arrived",
      "period": {
        "start": "2017-02-01T07:15:00+10:00",
        "end": "2017-02-01T07:35:00+10:00"
      }
    },
    {
      "status": "triaged",
      "period": {
        "start": "2017-02-01T07:35:00+10:00",
        "end": "2017-02-01T08:45:00+10:00"
      }
    },
    {
      "status": "in-progress",
      "period": {
        "start": "2017-02-01T08:45:00+10:00",
        "end": "2017-02-01T12:15:00+10:00"
      }
    },
    {
      "status": "onleave",
      "period": {
        "start": "2017-02-01T12:15:00+10:00",
        "end": "2017-02-01T12:45:00+10:00"
      }
    },
    {
      "status": "in-progress",
      "period": {
        "start": "2017-02-01T12:45:00+10:00"
      }
    }
  ],
  "class": {
    "system": "http://hl7.org/fhir/v3/ActCode",
    "code": "IMP",
    "display": "inpatient encounter"
  },
  "classHistory": [
    {
      "class": {
        "system": "http://hl7.org/fhir/v3/ActCode",
        "code": "EMER",
        "display": "emergency"
      },
      "period": {
        "start": "2017-02-01T07:15:00+10:00",
        "end": "2017-02-01T09:27:00+10:00"
      }
    },
    {
      "class": {
        "system": "http://hl7.org/fhir/v3/ActCode",
        "code": "IMP",
        "display": "inpatient encounter"
      },
      "period": {
        "start": "2017-02-01T09:27:00+10:00"
      }
    }
  ],
  "subject": {
    "reference": "Patient/example"
  },
  "period": {
    "start": "2017-02-01T07:15:00+10:00"
  },
  "hospitalization": {
    "admitSource": {
      "coding": [
        {
          "system": "http://hl7.org/fhir/admit-source",
          "code": "emd",
          "display": "From accident/emergency department"
        }
      ]
    }
  },
  "location": [
    {
      "location": {
        "display": "Emergency Waiting Room"
      },
      "status": "active",
      "period": {
        "start": "2017-02-01T07:15:00+10:00",
        "end": "2017-02-01T08:45:00+10:00"
      }
    },
    {
      "location": {
        "display": "Emergency"
      },
      "status": "active",
      "period": {
        "start": "2017-02-01T08:45:00+10:00",
        "end": "2017-02-01T09:27:00+10:00"
      }
    },
    {
      "location": {
        "display": "Ward 1, Room 42, Bed 1"
      },
      "status": "active",
      "period": {
        "start": "2017-02-01T09:27:00+10:00",
        "end": "2017-02-01T12:15:00+10:00"
      }
    },
    {
      "location": {
        "display": "Ward 1, Room 42, Bed 1"
      },
      "status": "reserved",
      "period": {
        "start": "2017-02-01T12:15:00+10:00",
        "end": "2017-02-01T12:45:00+10:00"
      }
    },
    {
      "location": {
        "display": "Ward 1, Room 42, Bed 1"
      },
      "status": "active",
      "period": {
        "start": "2017-02-01T12:45:00+10:00"
      }
    }
  ]
}`

And the response is `{
    "StatusElement": [
        "Element with min. cardinality 1 cannot be null"
    ],
    "Text.StatusElement": [
        "Element with min. cardinality 1 cannot be null"
    ],
    "StatusHistory[0].StatusElement": [
        "Element with min. cardinality 1 cannot be null"
    ],
    "StatusHistory[1].StatusElement": [
        "Element with min. cardinality 1 cannot be null"
    ],
    "StatusHistory[2].StatusElement": [
        "Element with min. cardinality 1 cannot be null"
    ],
    "StatusHistory[3].StatusElement": [
        "Element with min. cardinality 1 cannot be null"
    ],
    "StatusHistory[4].StatusElement": [
        "Element with min. cardinality 1 cannot be null"
    ]
}`

Any insights would be appreciated.

Thanks in advance

**Comment by PDRDaveF** [comment]
Thanks for getting back @mbaltus I'm using the inbuilt JSON.NET deserializer in net core 2.2?

`[HttpPost]
        [Route("")]
        public IActionResult Create([FromBody] Encounter encounter)
        {
            return CreatedAtAction(nameof(Retrieve), new { id = Guid.NewGuid() }, encounter);
        }`
Are there any JSON settings I need to implement?

**Comment by ewoutkramer** [comment]
Hi @PDRDaveF, you cannot use the built-in serializers for .NET, see https://stackoverflow.com/questions/21117815/hl7-fhir-serialisation-to-json-in-asp-net-web-api/21137069#21137069.

**Comment by PDRDaveF** [comment]
Ah! Thank you!
