### ISSUE TITLE
Validating a object in an Azure Function

### ISSUE THREAD

**Issue by PDRDaveF** [FirelyTeam/fhir-net-api#1011]
I am using the parser in an Azure Function, and wishing to validate the object, however when I call validate I'm not getting any validation errors?

Code:
`var body = await request.ReadAsStringAsync();

            var parser = new FhirJsonParser(ParserSettings.CreateDefault());

            var model = (Encounter)parser.Parse(body, typeof(Encounter));

            var test = new ValidationContext(model, null, null);

            var validationResults = model.Validate(test);`

Thanks in advance,

Dave

**Comment by ewoutkramer** [comment]
Hi @PDRDaveF - I do it slightly differently in my unit-tests: 
https://github.com/FirelyTeam/fhir-net-api/blob/develop-stu3/src/Hl7.Fhir.Core.Tests/Validation/ValidatePatient.cs

Can you check whether the approach in the unit-tests work for you?

**Comment by ewoutkramer** [comment]
no response, closing.
