### ISSUE TITLE
TransactionBuilder class is currently using Uri.ToString method

### ISSUE THREAD

**Issue by zonenature** [FirelyTeam/fhir-net-api#1040]
The TransactionBuilder class is currently using the Uri.ToString() method
( Related to https://github.com/FirelyTeam/fhir-net-api/pull/282 )

Branch: develop-dstu2-classic
File: https://github.com/FirelyTeam/fhir-net-api/blob/develop-dstu2-classic/src/Hl7.Fhir.Core/Rest/TransactionBuilder.cs
Line: 49 - private void addEntry(Bundle.EntryComponent newEntry, RestUrl path)

Tested with Path of the medication:
"https://services.sante.ca/fhir/dstu2/Medication/DILUANT - MMR II "
// Remark: trailing space in the name

Current code:

newEntry.Request.Url = path.Uri.ToString();
// Returns an unescaped representation of the Uri.
// ToString() Removes the encoding for the request Url
// -> "https://services.sante.ca/fhir/dstu2/Medication/DILUANT - MMR II "

Replace by:
   
var uriString = path.Uri.IsAbsoluteUri ? path.Uri.AbsoluteUri : path.Uri.OriginalString;
newEntry.Request.Url = uriString;
// Keeps the encoding for the request Url
// -> "https://services.sante.ca:443/fhir/dstu2/Medication/DILUANT%20-%20MMR%20II%20"

**Comment by ewoutkramer** [comment]
Hi @zonenature, yes I agree this ToString() must go - would you mind creating a PR?
