### ISSUE TITLE
R4: Update snapshot generator for type slicing

### ISSUE THREAD

**Issue by wmrutten** [FirelyTeam/fhir-net-api#1051]
Update the snapshot generator implementation according to changes discussed with Grahame at DevDays US in Redmond.

Specifically, type slice in snapshot should *always* include slicing component. Slicing component may be omitted from the differential (implicit/redundant for type slice); in that case, the generator should emit a default type slicing component to the snapshot.

WARNING! R4 API packages did NOT process type slices correctly. Once this has been fixed, customers will have to re-generate some existing snapshots.

**Comment by wmrutten** [comment]
TODO: Implement Grahame's Snapshot unit tests

https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.r5/src/test/resources/snapshot-generation/manifest.xml

**Comment by wmrutten** [comment]
Test results are published here:
https://gist.github.com/wmrutten/acc5e24601eb74df582ff39b21f41efc

**Comment by ewoutkramer** [comment]
Fixed for R4 in #1088
