### ISSUE TITLE
R4 SnapshotGenerator: Fix ElementDefinition.Base for newly introduced elements

### ISSUE THREAD

**Issue by wmrutten** [FirelyTeam/fhir-net-api#1053]
Example: core StructureDefinition for `Resource`
* Introduces element `Resource.id` (0...1, type=`Id`)
* Inherits from `Id` StructureDefinition root element (0...*)

=> Initialize `ElementDefinition.Base` for path=`Resource.id` as:
```
Path = `Resource.id`
Min = 0
Max = 1
```

Specifically, initialize Base cardinality from defining (diff) element definition itself.
Do NOT inherit Base cardinality from parent element definition!

**Comment by cknaap** [comment]
It looks like this is merged into develop1.x/r4, so therefore putting it into the Sprint 2019.4.
