### ISSUE TITLE
Base class should claim support for INotifyPropertyChanged

### ISSUE THREAD

**Issue by wmrutten** [FirelyTeam/fhir-net-api#1056]
The common `INotifyPropertyChanged` interface (from `System.ComponentModel`) requires the implementation of a single `PropertyChanged` event. The common `Base` class exposes the `PropertyChanged` event. However `Base` does not yet claim to support the `INotifyPropertyChanged` interface. Propose to add this interface, as the implementation is already in place.

**Comment by ewoutkramer** [comment]
Sure! Send me a PR ;-)

**Comment by wmrutten** [comment]
https://github.com/FirelyTeam/fhir-net-common/pull/2

**Comment by ewoutkramer** [comment]
This also meant I could remove this interface from all subclasses. Did that while reviewing the generated classes for 2.0
