### ISSUE TITLE
Bundle Create always adds /TypeName to the baseUri

### ISSUE THREAD

**Issue by bthaens** [FirelyTeam/fhir-net-api#1066]
Why does the TransactionBuilder.Create add the TypeName to the base uri?

Our bundle gets posted to http://touchstone.aegis.net:55953/fhir3-i2/Bundle in stead of http://touchstone.aegis.net:55953/fhir3-i2

Is there a reason to do this or a way to skip this (our client wants the bundle to be posted to the base uri)?

**Comment by mbaltus** [comment]
The TransactionBuilders is used to construct a batch or transaction type Bundle with entries in it that list all of the interactions you want to perform on the server in one go.
TransactionBuilder.Create will add an entry to the Bundle with a POST request in it, plus the resource that you give as argument. It is not used to make the transaction Bundle itself - that is implicit in the new TransactionBuilder object.

After you have constructed the transaction Bundle, you can send it to the server endpoint with the FhirClient.Transaction and TransactionBuilder.ToBundle methods, like this:

            var result = client.Transaction(myTransaction.ToBundle());

**Comment by bthaens** [comment]
So it is not possible to use the FhirClient.CreateAsync<Bundle> functionality for this?
Can you show a snippet to construct the myTransaction?

**Comment by mbaltus** [comment]
Correct, you cannot use the FhirClient.Create methods, since a Create in FHIR means creating the resource according to the resource type you send the data to. A transaction or batch is a different type of interaction (see https://www.hl7.org/fhir/http.html). However, there is also a FhirClient.TransactionAsync for when you want to send the transaction asynchronously.

Example snippet:

```
var myTransaction = new TransactionBuilder("https://vonk.fire.ly", Bundle.BundleType.Transaction);

var myPat = new Patient();
// fill myPat with values
myPat.Name.Add(new HumanName().WithGiven("Mirjam").AndFamily("Baltus"));
// add create interaction to transaction
myTransaction.Create(myPat);

var examplePat = client.Read<Patient>("Patient/example");
// change something
examplePat.BirthDate = "1983-05-12";
// add update interaction to transaction
myTransaction.Update(examplePat.Id, examplePat);

var result = client.Transaction(myTransaction.ToBundle());
```

**Comment by bthaens** [comment]
Thanks for your quick responses. I managed to fill a transaction with some Creates. 
While the CreateAsync gave me a correct response, the transaction is now returning an error:

 "text": "Resource syntax or data is incorrect or invalid, and cannot be used to create a new resource. JsonNull"

Full request is here: 
`{
	"resourceType": "Bundle",
	"type": "batch",
	"entry": [
		{
			"resource": {
				"resourceType": "Patient",
				"id": "selfmeasurement-patient-kwalificatie1-370",
				"meta": {
					"profile": [
						"http://fhir.nl/fhir/StructureDefinition/nl-core-patient"
					]
				},
				"text": {
					"status": "generated",
					"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Hagemeier</div>"
				},
				"identifier": [
					{
						"system": "http://example-xis.org/fhir/NamingSystem/patientID",
						"value": "1000000001"
					}
				],
				"name": [
					{
						"use": "official",
						"family": "Hagemeier",
						"_family": {
							"extension": [
								{
									"url": "http://hl7.org/fhir/StructureDefinition/iso21090-EN-qualifier",
									"valueString": "Hagemeier"
								}
							]
						},
						"_given": [
							{
								"extension": [
									{
										"url": "http://hl7.org/fhir/StructureDefinition/iso21090-EN-qualifier",
										"valueCode": "BR"
									}
								]
							}
						]
					}
				],
				"gender": "male",
				"birthDate": "1975-01-10",
				"address": [
					{
						"line": [
							"Defaultstreet 0"
						],
						"_line": [
							{
								"extension": [
									{
										"url": "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetName",
										"valueString": "Defaultstreet"
									},
									{
										"url": "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-houseNumber",
										"valueString": "0"
									}
								]
							}
						],
						"city": "Defaultcity",
						"postalCode": "Defaultpostalcode"
					}
				]
			},
			"request": {
				"method": "POST",
				"url": "Patient"
			}
		},
		{
			"resource": {
				"resourceType": "Observation",
				"id": "5ca4d48a7f004cdda72ecce01ac4a632",
				"meta": {
					"profile": [
						"http://nictiz.nl/fhir/StructureDefinition/zib-BloodPressure"
					]
				},
				"text": {
					"status": "generated",
					"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Generated Narrative with Details</b></p><p><b>status</b>: Final</p><p><b>category</b>: vital-signs</p><p><b>code</b>: Blood pressure panel with all children optional</p><p><b>subject</b>: Patient/selfmeasurement-patient-kwalificatie1-370</p><p><b>effective</b>: 2019-08-02T16:15:00+02:00</p><p><b>performer</b>: Patient/selfmeasurement-patient-kwalificatie1-370</p><h3>Value</h3><table><tr><th>Value</th><th></th></tr><tr><td>100/80</td><td>mm[Hg]</td></tr></table></div>"
				},
				"status": "final",
				"category": [
					{
						"coding": [
							{
								"system": "http://hl7.org/fhir/observation-category",
								"code": "vital-signs",
								"display": "vital-signs"
							}
						],
						"text": "vital-signs"
					}
				],
				"code": {
					"coding": [
						{
							"system": "http://loinc.org",
							"code": "85354-9",
							"display": "Blood pressure panel with all children optional"
						}
					],
					"text": "Blood pressure panel with all children optional"
				},
				"subject": {
					"reference": "Patient/selfmeasurement-patient-kwalificatie1-370",
					"display": "Hagemeier"
				},
				"effectiveDateTime": "2019-08-02T16:15:00+02:00",
				"performer": [
					{
						"reference": "Patient/selfmeasurement-patient-kwalificatie1-370",
						"display": "Hagemeier"
					}
				],
				"bodySite": {
					"coding": [
						{
							"system": "http://snomed.info/sct",
							"code": "368208006",
							"display": "Linker bovenarm"
						}
					],
					"text": "Linker bovenarm"
				},
				"component": [
					{
						"code": {
							"coding": [
								{
									"system": "http://loinc.org",
									"code": "8480-6"
								}
							],
							"text": "Systolic blood pressure"
						},
						"valueQuantity": {
							"value": 100,
							"unit": "mm[Hg]",
							"system": "http://unitsofmeasure.org",
							"code": "mm[Hg]"
						}
					},
					{
						"code": {
							"coding": [
								{
									"system": "http://loinc.org",
									"code": "8462-4"
								}
							],
							"text": "Diastolic blood pressure"
						},
						"valueQuantity": {
							"value": 80,
							"unit": "mm[Hg]",
							"system": "http://unitsofmeasure.org",
							"code": "mm[Hg]"
						}
					}
				]
			},
			"request": {
				"method": "POST",
				"url": "Observation"
			}
		}
	]
}`

**Comment by mbaltus** [comment]
I think that's because your data cannot be validated. The Bundle was probably only validated to see if the Bundle was correct, but now with the batch, the separate resources inside are validated. This is what I get when I try to validate your data:

```
{
  "resourceType": "OperationOutcome",
  "id": "64a98c10-0a83-43b3-83f2-337c2416690e",
  "meta": {
    "versionId": "0fc5d993-7a71-45ed-899c-e33b56a9b87d",
    "lastUpdated": "2019-08-06T14:21:38.168247+00:00"
  },
  "issue": [
    {
      "severity": "error",
      "code": "invalid",
      "details": {
        "coding": [
          {
            "system": "http://hl7.org/fhir/dotnet-api-operation-outcome",
            "code": "1003"
          }
        ],
        "text": "The declared type of the element (code) is incompatible with that of the instance ('string')"
      },
      "location": [
        "Bundle.entry[0].resource[0].name[0].family[0].extension[0].valueString[0]"
      ]
    },
    {
      "severity": "error",
      "code": "code-invalid",
      "details": {
        "coding": [
          {
            "system": "http://hl7.org/fhir/dotnet-api-operation-outcome",
            "code": "6001"
          }
        ],
        "text": "Code 'Hagemeier' from system '' does not exist in valueset 'http://hl7.org/fhir/ValueSet/name-part-qualifier'"
      },
      "location": [
        "Bundle.entry[0].resource[0].name[0].family[0].extension[0].valueString[0]"
      ]
    }
  ]
}
```

If you need further help, could we pick this up through email (fhirapi at fire dot ly)?
