### ISSUE TITLE
FhirParser skips valid element

### ISSUE THREAD

**Issue by mmsmits** [FirelyTeam/fhir-net-api#1071]
In the attached file:

```DocumentReference.masterIdentifier.value``` gets a null value when parsed using the FhirXmlParser. 

[missingElement.txt](https://github.com/FirelyTeam/fhir-net-api/files/3481640/missingElement.txt)

![image](https://user-images.githubusercontent.com/8956842/62702702-c2e6cb80-b9e7-11e9-83d0-c91405223ea1.png)

**Comment by brianpos** [comment]
That's strange!

**Comment by mmsmits** [comment]
I encountered it in the example below as well. On Observation.valueQuantity.value:

[missingElement2.txt](https://github.com/FirelyTeam/fhir-net-api/files/3520491/missingElement2.txt)

Probably something to do with elements called "value"

**Comment by ArdonToonstra** [comment]
Also noted in an example where identifier.value is missing: https://simplifier.net/Basisprofil-DE-R4/Practitioner-example/~xml

**Comment by wmrutten** [comment]
Could this be related to #999 ?

**Comment by wardweistra** [comment]
@ewoutkramer [mentioned on Zulip](https://chat.fhir.org/#narrow/stream/179171-dotnet/topic/Validation.20errors/near/176965791):
> We found the cause of the issue. Although we agree the error is very unclear, it does mean you did not put your xml elements in the http://hl7.org/fhir namespace! We will fix this in the next update...
