### ISSUE TITLE
MolecularSequence Resource

### ISSUE THREAD

**Issue by shanthuk** [FirelyTeam/fhir-net-api#1073]
How can I work with **MolecularSequence** Resource?

**Comment by ewoutkramer** [comment]
It's available in the R4 version of the libraries, so then you can work with it like any other resource (e.g. like Patient).

**Comment by shanthuk** [comment]
Can I install this nuget package in my visual studio ?

**Comment by ewoutkramer** [comment]
Yes, just search for "FHIR" and look for something with "Core" and ".R4" in the name.
