### ISSUE TITLE
Incorrect maximum cardinality displayed in all views (diff/hybrid/snap)

### ISSUE THREAD

**Issue by vadi2** [FirelyTeam/fhir-net-api#1108]
https://simplifier.net/SwedishNationalMedicationList/DoseRange/~overview using the 07/10/2019 14:36:01 version shows that `low` and `high` have `1..` cardinality. This is invalid FHIR, and that is not what the profile author has done: they only set the minimum cardinality to `1` - see the raw xml/json.

Simplifier is incorrectly inferring that the maximum cardinality has been set to `*` when in reality it was unchanged and should inherit `1` from the base profile.

https://simplifier.net/SwedishNationalMedicationList/NLLDosage/~overview also shows this in maxDosePerPeriod.

An internal review by @mmsmits and @wardweistra concluded that the issue is in the snapshot generator.

**Comment by wmrutten** [comment]
It's a subtle issue. Forge displays warnings about invalid constraints, i.e. user constraints that violate the base profile. If the SnapshotGenerator would automatically correct invalid constraints specified in the differential, then this would prevent Forge/validator from detecting errors...

So I think what we need:
(1) Merge base profile & (optional) element type profile constraints, by calculating the "intersection"; e.g. minimum cardinality takes priority. This ensures that externally referenced profiles can never cause violations.
Note: currently, type profile constraints simply override/replace base profile constraints, even if invalid. We would need to replace this with proper intersection logic.
(2) Apply constraints as specified in the differential, by replacing/overriding the merged base constraints calculated in step (1). Do NOT calculate intersection. The calculated snapshot may violate base constraints from (1), which a client can detect and report.

**Comment by ArdonToonstra** [comment]
Is this related to https://github.com/FirelyTeam/fhir-net-api/issues/1303 ?

**Comment by vadi2** [comment]
Yes, that issue seems similar.
