### ISSUE TITLE
FhirClient SearchAsync not thread safe

### ISSUE THREAD

**Issue by oldefezziwig** [FirelyTeam/fhir-net-api#1110]
I am able to reproduce this issue pretty reliably, using both Hl7.Fhir.STU3 0.96.0.0 and 1.3.0 (When we run this, one of those Assert.IsTrue()'s eventually fail for us).  Here is my test code (uses NUnit 3.10.0).  There are some helper methods and whatnot that we've implemented (i.e. the "retryPolicyFactory" just supports the ability to retry any operation a few times if they fail for any reason, the _patientRootOid could be just any old OID, and the FhirClient here is actually a wrapper because we need to inject an OAUTH token header for each request), but none of that should have a bearing on the results of the test.

Using _numParallelThreads = 15 for the purposes of this test.

Also, when we spin up multiple FhirClients (or possibly create a new one at the beginning of every iteration of the Parallel.ForEach), this issue does not occur.  So is that a valid solution or workaround (i.e. to ensure each separately running Task is using its own FhirClient instance)?
We were under the impression that a single FhirClient instance should be used by multiple concurrent Tasks, but per this test that does not appear to be the case.

If anyone is able to reproduce this issue, please comment back here as this is becoming a real operational headache for us.  Thanks!

`[Test]
    public async System.Threading.Tasks.Task TestFhirClientCallsInParallel()

    {
      // Generate patients
      var patients = new List<Patient>();
      for (int i = 1; i < 2000; i++)
      {
        patients.Add(new Patient
        {
          Name = new List<HumanName>
          {
            new HumanName
            {
              Family = $"Doe{i}",
              Given = new List<string>
              {
                $"John{i}"
              }
            }
          },
          Identifier = new List<Identifier>
          {
            new Identifier(_patientRootOid, i.ToString())
            {
              Use = Identifier.IdentifierUse.Official,
              Type = new CodeableConcept("http://hl7.org/fhir/v2/0203", "MR")
            }
          }
        });
      }

      await System.Threading.Tasks.Task.Factory.StartNew(() =>
        Parallel.ForEach(patients, new ParallelOptions
        {
          MaxDegreeOfParallelism = _numParallelThreads
        }, async patient =>
        {
          // Use single FhirClient (instantiated as a private var)
          var client =  _fhirCient;

          Console.WriteLine($"Processing Patient {patient.Identifier.FirstOrDefault()?.Value}");
          // create patient
          var createdPatient = await client.CreateAsync(patient, _retryPolicyFactory.CreateCatalystRetryPolicy());
          Assert.NotNull(createdPatient);
          Assert.IsTrue(patient.Identifier.IsExactly(createdPatient.Identifier));

          // query for patient
          var queriedPatientBundle = await client.SearchAsync<Patient>(new[] {$"identifier={patient.Identifier.FirstOrDefault()?.System}|{patient.Identifier.FirstOrDefault()?.Value}"}, _retryPolicyFactory.CreateCatalystRetryPolicy());
          var queriedPatient = queriedPatientBundle?.Entry?.ByResourceType<Patient>()?.FirstOrDefault();
          Assert.NotNull(queriedPatient);
          Assert.IsTrue(patient.Identifier.IsExactly(queriedPatient.Identifier), $"First search for identifier {JsonConvert.SerializeObject(patient.Identifier)} but returned {JsonConvert.SerializeObject(queriedPatient.Identifier)}");

          // update patient
          queriedPatient.Name.FirstOrDefault()?.GivenElement.Add(new FhirString("Q"));
          var updatedPatient = await client.UpdateAsync(queriedPatient, _retryPolicyFactory.CreateCatalystRetryPolicy());
          Assert.NotNull(updatedPatient);
          Assert.IsTrue(patient.Identifier.IsExactly(updatedPatient.Identifier));

          // query for patient (2nd)
          queriedPatientBundle = await client.SearchAsync<Patient>(new[] {$"identifier={patient.Identifier.FirstOrDefault()?.System}|{patient.Identifier.FirstOrDefault()?.Value}"}, _retryPolicyFactory.CreateCatalystRetryPolicy());
          queriedPatient = queriedPatientBundle?.Entry?.ByResourceType<Patient>()?.FirstOrDefault();
          Assert.NotNull(queriedPatient);
          Assert.IsTrue(patient.Identifier.IsExactly(queriedPatient.Identifier), $"Second search for identifier {JsonConvert.SerializeObject(patient.Identifier)} but returned {JsonConvert.SerializeObject(queriedPatient.Identifier)}");

          // update patient (2nd)
          queriedPatient.Gender = AdministrativeGender.Male;
          updatedPatient = await client.UpdateAsync(queriedPatient, _retryPolicyFactory.CreateCatalystRetryPolicy());
          Assert.NotNull(updatedPatient);
          Assert.IsTrue(patient.Identifier.IsExactly(updatedPatient.Identifier));

          // query for patient
          queriedPatientBundle = await client.SearchAsync<Patient>(new[] {$"identifier={patient.Identifier.FirstOrDefault()?.System}|{patient.Identifier.FirstOrDefault()?.Value}"}, _retryPolicyFactory.CreateCatalystRetryPolicy());
          queriedPatient = queriedPatientBundle?.Entry?.ByResourceType<Patient>()?.FirstOrDefault();
          Assert.NotNull(queriedPatient);
          Assert.IsTrue(patient.Identifier.IsExactly(queriedPatient.Identifier), $"Third search for identifier {JsonConvert.SerializeObject(patient.Identifier)} but returned {JsonConvert.SerializeObject(queriedPatient.Identifier)}");

          // delete patient
          await client.DeleteAsync(queriedPatient, _retryPolicyFactory.CreateCatalystRetryPolicy());
        })
      );
    }`

**Comment by ewoutkramer** [comment]
Good catch, I can see how that causes confusion.  @mbaltus would you be able to change that into something that does not suggest to use a single client per thread?

**Comment by ewoutkramer** [comment]
@mbaltus - can you change this line.

Also, we need to take the documentation on github.io offline - its wildly outdated.

**Comment by ewoutkramer** [comment]
Updated the documentation AND redirected the users away from the github.io pages.

**Comment by oldefezziwig** [comment]
@ewoutkramer I see that you updated the documentation to show the following:
> Note: the FhirClient is not thread-safe, so you will need to create one for each thread, if necessary. But don’t worry: creating an instance of a FhirClient is cheap, the connection will not be opened until you start working with it.
Can you verify that this is still the case in the new 2.x version that uses HttpClient?  Or is that new version threadsafe and the proper usage when used in parallel (using the async framework) is to just create a single FhirClient per endpoint even if it may be used in parallel (like in https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.parallel.foreach?view=net-5.0 for example)?

**Comment by ewoutkramer** [comment]
Yes, option b.  We want to keep the options open that we cache stuff or do non-threadsafe things in our implementations.

There are only a few classes (mostly around caching) in the SDK that are threadsafe. So we *could* do it if there's a strong usecase to have a single instance. But I haven't heard one so far.

**Comment by oldefezziwig** [comment]
@ewoutkramer sorry I'm still confused about what we are supposed to do here.  We need to process messages in parallel using a mechanism similar to the one shown in my first message back in https://github.com/FirelyTeam/firely-net-sdk/issues/1110#issue-492820197

We now have realized that we need to use the 2.x FhirClient (and do like that it uses HttpClient), so we are in a bit of a bind as to how to use it in parallel.  If you look at the test code I posted when I created this ticket, which one of the following should be the suggested usage for FhirClient 2.0?

1. As-is in the code above, meaning FhirClient is a singleton hitting the same endpoint (recall that this approach did *not* work for 1.x)
2. Instead of the line `var client =  _fhirCient;` it would be `var client =  new FhirClient("http://server.fire.ly");` created for every iteration of the parallel loop (this is essentially what we had to do to get 1.x to work, but there are a lot of warnings about bad side effects of instantiating multiple HttpClients on the same endpoint in the same process: https://social.msdn.microsoft.com/Forums/en-US/4e12d8e2-e0bf-4654-ac85-3d49b07b50af/best-practice-usage-of-httpclient-for-rest-calls-maximum-throughput?forum=netfxnetcom).  Note that we didn't test this approach yet using FhirClient 2.0, but were concerned about these warnings and were under the impression that anytime you used HttpClient, you should just create one per endpoint in a given process.

**Comment by ewoutkramer** [comment]
I was going to say:

>So if it is ok to essentially create a separate FhirClient per concurrent processing workflow (i.e. for the life of a given Task, that may make multiple requests based on a single quantity of incoming data), then we will just do that for now. Thanks again!!

This is your solution. But then I read:

> we have read a lot of warnings about bad side effects of instantiating multiple HttpClients for the same endpoint in the same process

Well, I guess that is right. Because looking at the code, if you'd fire a large number of parrallel request you'd literally be swamping the target server and (on a lower level) the available interrupts on your own machine.  The target server's owner (unless that is you), might not really enjoy being targeted this way!

So, the more advanced approach on having a pool seem to make sense, but that of course limits your parrallelism.

**Comment by stonstad** [comment]
I think this topic may need to be revisited.  Support for thread safety is a fundamental feature of a RESTful client.

**Comment by ewoutkramer** [comment]
This would mean writing a totally new FhirClient - the current one is fundamentally stateful.

**Comment by ewoutkramer** [comment]
What would be needed?  Getting a fresh (stateful) client out of a pool of clients for the same endpoint with the same authentication settings like discussed above? I personally have never needed thread safety, instead have created a new instance of the client, so I'd like to get a better feel of where the client is deficient currently.

**Comment by ewoutkramer** [comment]
I guess what we need to do is centered around these best-practices? 

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-6.0

**Comment by ewoutkramer** [comment]
https://github.com/FirelyTeam/firely-net-sdk/issues/2036 - according to @brianpos we should be alright in this regard.

**Comment by oldefezziwig** [comment]
@ewoutkramer @brianpos so are you saying that if we use the version with feature #2036 that we should now be safe to use HttpClientFactory to create a new FhirClient for each new request (as opposed to a pool of clients or a single client, both approaches as described above each have their own drawbacks)?  Put another way, this gets around the issues described in https://www.aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/ ?
