### ISSUE TITLE
DateTime format issue

### ISSUE THREAD

**Issue by KasperDamgaard** [FirelyTeam/fhir-net-api#1114]
Hey
I am not sure where exactly the bug resides, but whenever I post to a specific Hapi fhir server with a payload containing a DateTime formatted string, the server complains about "Temporal precision not supported: SECOND". This is when sending e.g. ”2019-09-16T14:00:00+02:00” as the start field in an Appointment. This is what firely will use in the json blob that is sent.
If I change this manually to "2019-09-16T14:00:00.000+02:00” then it works as intended. 
This is both an issue when creating new resources and updating old ones.

My question is therefore twofold: 
1) Where does the error reside? In Firely or Hapi? (loaded question, I know :) )
2) In either case, can I manipulate the date formatter to print milliseconds as well?

Thanks for the support in advance!
/Kasper

**Comment by cknaap** [comment]
Appointment,start if of type 'instant', that must be down to the second at least. So milliseconds are optional. See http://hl7.org/fhir/R4/datatypes.html#instant.
Could you check that with HAPI?

Note: You don't specify whether you work with STU3 or R4, but the precision requirements for instant are the same for both.

**Comment by KasperDamgaard** [comment]
I do not have access to the Hapi server, so all I could do would be to read the documentation, but it should abide by the standard (which by the way is DSTU2). 
I also read the standard as being optional for milliseconds, but "at least to the second" could maybe also mean that it is ok to require milliseconds? If that is the case, it would be nice for Firely to have the option of adding milliseconds.

**Comment by KasperDamgaard** [comment]
I checked the Hapi documentation and found that by default millisecond precision is used. See https://github.com/jamesagnew/hapi-fhir/blob/dstu2_final/hapi-fhir-base/src/main/java/ca/uhn/fhir/model/primitive/InstantDt.java 

Thus, unless the server implementation specifically allows second precision, milliseconds are enforced by default.

**Comment by ewoutkramer** [comment]
The output of this element depends on how you have initialized the field:

* `Appointment.Start = new Instant(DateTimeOffset.Now)`  
would result in millisecond precision.

* `Appointment.Start = new Instant(new DateTimeOffset(2016,1,1,13,45,56,345,TimeSpan.Zero))`  
would result in millisecond precision.

* `Appointment.Start = new Instant(new DateTimeOffset(2016,1,1,13,45,56,TimeSpan.Zero))`  
would *not* have millisecond precision.

How are you initializing this field?

**Comment by ewoutkramer** [comment]
But yes, HAPI should accept it without milliseconds.

**Comment by ewoutkramer** [comment]
I have talked to James, he's acknowledged this is an error on his side.

**Comment by KasperDamgaard** [comment]
Great news. I also convinced the Hapi server ppl to accept it as their problem. Thanks for the quick support and a great product!
