### ISSUE TITLE
ParseXml of ContactPoint does not set value

### ISSUE THREAD

**Issue by kennethaamodt** [FirelyTeam/fhir-net-api#1121]
Given the xml below FhirXmlParser.ParseXml does not set the value, system and use are set .

`<contactpoint>
    <system value="phone" />
    <value value="12534" />
    <use value="mobile" />
</contactpoint>`

`
var pser = new FhirXmlParser(new ParserSettings { DisallowXsiAttributesOnRoot = false });
var contactpoint = pser.Parse(tpXml,typeof(ContactPoint));
`

This works as expected however (giving the same xml as above):
`
var contactPoint = new ContactPoint(ContactPoint.ContactPointSystem.Phone, ContactPoint.ContactPointUse.Mobile,"12534");
var xml = contactPoint.ToXml()
`

Am I missing something?

**Comment by ewoutkramer** [comment]
Could this be linked to #1071?  It's again the "value" element, and yes there's some special handling around that.

**Comment by kennethaamodt** [comment]
Yes, looks like they are related.

**Comment by gstoian** [comment]
This https://github.com/FirelyTeam/fhir-net-common/pull/7 should fix it.
