### ISSUE TITLE
FhirPath expression node constructors should call its IEnumerable args only once

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/fhir-net-api#1128]
If you look at this code from ExpressionNode.cs in the fhirpath engine:

```
        public FunctionCallExpression(Expression focus, string name, TypeSpecifier type, IEnumerable<Expression> arguments, ISourcePositionInfo location = null) : base(type, location)
        {
            if (string.IsNullOrEmpty(name)) throw Error.ArgumentNull("name");
            Focus = focus;
            FunctionName = name;
            Arguments = arguments ?? throw Error.ArgumentNull("arguments");
        }
```

We see that the IEnumerable arguments is stored in Arguments.  Whenever a visitor passes over this node and uses Argument multiple times, IEnumerable is evaluated over and over again, possibily triggering expensive re-visiting of the expression passed into the argument.

We should change Arguments to an array, and call ToArray() once in the constructor.

**Comment by marcovisserFurore** [comment]
@gstoian: I see that you are done developing, but is there also a pull request of this issue?

**Comment by brianpos** [comment]
Can you include me on the PR review? As wanting to check what this to array is in.
For things like large codesystems or lists it can be super expensive if not required...

**Comment by gstoian** [comment]
https://github.com/FirelyTeam/fhir-net-common/pull/11
