### ISSUE TITLE
Client fails requests when server respond with success codes different than 200

### ISSUE THREAD

**Issue by michelemottini** [FirelyTeam/fhir-net-api#1129]
See https://github.com/FirelyTeam/fhir-net-api/blob/develop-stu3/src/Hl7.Fhir.Core/Rest/FhirClient.cs#L869 - at least 204 and probably 201 should be consider valid as well

**Comment by michelemottini** [comment]
See also discussion at https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Operations.20with.20no.20'out'.20parameters

**Comment by ewoutkramer** [comment]
seems fair.

**Comment by brianpos** [comment]
An existing operation that has more than just this result is this one.
http://hl7.org/fhir/messageheader-operation-process-message.html
