### ISSUE TITLE
[validation of xml] instance with and without xmlns namespace changes outcome of validator in a unexpected manor.

### ISSUE THREAD

**Issue by furoreSebastiaan** [FirelyTeam/fhir-net-api#1131]
Reproduction path:

1. Validate [Organization-example (1).zip](https://github.com/FirelyTeam/fhir-net-api/files/3663303/Organization-example.1.zip)

against package: hl7.fhir.no.basis 2.0.7

2. See that there are no issues.

3. Remove the namespace xmlns="http://hl7.org/fhir" from the xml

4. validate again against the same package
5. see the following error: 

Invalid : Instance count for 'Organization.identifier.value' is 0, which is not within the specified cardinality of 1..1

Which is strange for removing the xmlns.. Can anybody tell me what is the problem here?

**Comment by wmrutten** [comment]
The XML namespace is mandatory.
http://hl7.org/fhir/xml.html#2.6.1

> FHIR elements are always in the namespace http://hl7.org/fhir . This is usually specified as the default namespace on the root element.

**Comment by furoreSebastiaan** [comment]
Couldn't that be emitted as an error then? Now a totally different error is shown that has nothing to do with the missing namespace.

**Comment by wmrutten** [comment]
Definitely, the API should always try to provide useful error messages with detailed error info.
I propose we keep this issue open in order to improve error reporting.

**Comment by wardweistra** [comment]
So also related to #1071?

**Comment by gstoian** [comment]
Yes, it is related to #1071 , a PR was created to fix this.

**Comment by marcovisserFurore** [comment]
_Enhancement:_
When the xml namespace is omitted, then we want a better validation error.

**Comment by marcovisserFurore** [comment]
Issue #1071 solves also this issue. 

When you parse your resource with `permissiveParsing = true`, then no error will be thrown. This is also the default behavior. When permissive parsing has been switched off, then the parser will throw an exception, like this:
```
Parser: The element 'id' has no namespace, expected the HL7 FHIR namespace (http://hl7.org/fhir) (at line 2, 4)
```

You can switch off permissive parsing like this:
```
  var settings = new ParserSettings() { PermissiveParsing = false };
  var poco = (new FhirXmlParser(settings)).Parse<Patient>(xml).ToTypedElement();
```
