### ISSUE TITLE
FhirClient.LastResponse is disposed

### ISSUE THREAD

**Issue by michelemottini** [FirelyTeam/fhir-net-api#1132]
Because it is set within a `using` clause: https://github.com/FirelyTeam/fhir-net-api/blob/develop-stu3/src/Hl7.Fhir.Core/Rest/Requester.cs#L103 . . . and so it cannot really be used for anything (eg see https://referencesource.microsoft.com/#system/net/system/Net/HttpWebResponse.cs,302)

**Comment by brianpos** [comment]
Apart from within the AfterResponse call, but that is in the parameters anyway...

**Comment by brianpos** [comment]
If it is not going to be disposed here, probably needs to dispose the last call before it re-assigns it, and also in the Dispose() of the client.

**Comment by michelemottini** [comment]
I don't think it is a good idea not to dispose those (and possibly keep connections open) - my solutions was to remove the properties: https://github.com/CareEvolution/fhir-net-api/commit/5389b187c4dd6c5dafff692016defa1163b928a7

**Comment by brianpos** [comment]
I'm a big fan of that too, removing all those "last" properties, and allow it to be thread safe.

**Comment by ewoutkramer** [comment]
Yes, these properties are fundamentally broken. I noticed it before, but forgot about it (#833).  We should mark these as obsolete in 1.x, since we cannot remove them, but remove them in 2.x
