### ISSUE TITLE
Issue accessing information inside Bundle

### ISSUE THREAD

**Issue by asharma-carecloud** [FirelyTeam/fhir-net-api#1142]
Trying to use the `FHIRpath` in C#

Sample Code: 
```csharp 
var parser = new Hl7.Fhir.Serialization.FhirJsonParser();
var serializedBundle = JsonConvert.SerializeObject(bundle, new JsonSerializerSettings()
    {
       ContractResolver = new CamelCasePropertyNamesContractResolver(),
       DateFormatString = "yyyy-MM-ddTHH:mm:ss.fffZ",
       NullValueHandling = NullValueHandling.Ignore
    });
var parsedBundle = parser.Parse<Hl7.Fhir.Model.Bundle>(serializedBundle);
var nav = parsedBundle.ToTypedElement();
var result = nav.Select("entry.resource.Patient.name.first().prefix");
var value = result.FirstOrDefault()?.Value;
``` 

Path:  **`entry.resource.Patient.name.first().prefix`**

Getting the following error:

```
System.InvalidOperationException: Invocation of 'builtin.children' failed: Invocation of 'first' failed: Invocation of 'builtin.children' failed: Resource type name may only appear at the root of a document
   at Hl7.FhirPath.Expressions.InvokeeFactory.<>c__DisplayClass13_0.<Invoke>b__0(Closure ctx, IEnumerable`1 _)
   at Hl7.FhirPath.FhirPathCompiler.<>c__DisplayClass11_0.<Compile>b__0(ITypedElement focus, EvaluationContext ctx)
   at Hl7.FhirPath.IValueProviderFPExtensions.Select(ITypedElement input, String expression, EvaluationContext ctx)
```

**Sample Payload**: 
```javascript 
{
    "id": "4e5b0a5c-fee2-45d6-af72-782ea5b361a8",
    "resourceType": "Bundle",
    "type": "searchset",
    "entry": [
        {
            "fullUrl": "Patient/41b5a356-bda2-4d9f-889a-e9f809040395",
            "resource": {
                "id": "41b5a356-bda2-4d9f-889a-e9f809040395",
                "resourceType": "Patient",
                "active": true,
                "name": [
                    {
                        "use": "official",
                        "text": "Charlie H. Franco",
                        "family": "Franco",
                        "given": [
                            "Charlie",
                            "H."
                        ],
                        "prefix": [
                            "prefix_mr"
                        ]
                    },
                    {
                        "use": "nickname",
                        "text": "Charlie"
                    }
                ],
                "telecom": [
                    {
                        "system": "phone",
                        "value": "9042171261",
                        "use": "mobile",
                        "rank": 1
                    }
                ],
                "gender": "male",
                "birthDate": "1932-03-15",
                "address": [
                    {
                        "text": "23 Alpha Avenue, Jacksonville, Florida 32216",
                        "line": [
                            "23 Alpha Avenue"
                        ],
                        "city": "Jacksonville",
                        "state": "FL - Florida",
                        "postalCode": "32216",
                        "country": "US - United States of America"
                    }
                ],
                "maritalStatus": {
                    "coding": [
                        {
                            "system": "http://hl7.org/fhir/v3/MaritalStatus",
                            "code": "M",
                            "display": "Married"
                        }
                    ]
                },
                "managingOrganization": {
                    "reference": "Organization/598a0558-3edd-4621-985e-8fdcf4c58c04"
                }
            }
        }
    ]
}
```

**Comment by brianpos** [comment]
No need for the patient in that path.

**Comment by marcovisserFurore** [comment]
To check if you a valid resource (in this case a Bundle), you can use the following snippet:
```c#
            var nav = parsedBundle.ToTypedElement();
            var validator = new Validator();
            var results = validator.Validate(nav);
```

In your case you will get some errors because of the issues @brianpos mentioned above.

**Comment by asharma-carecloud** [comment]
> To check if you a valid resource (in this case a Bundle), you can use the following snippet:
> 
> ```cs
>             var nav = parsedBundle.ToTypedElement();
>             var validator = new Validator();
>             var results = validator.Validate(nav);
> ```
> 
> In your case you will get some errors because of the issues @brianpos mentioned above.

Thanks Marco, 
Which import is required for `var validator = new Validator();` I have the `https://www.nuget.org/packages/Hl7.FhirPath` installed (version 1.3.0)

**Comment by marcovisserFurore** [comment]
> > To check if you a valid resource (in this case a Bundle), you can use the following snippet:
> > ```cs
> >             var nav = parsedBundle.ToTypedElement();
> >             var validator = new Validator();
> >             var results = validator.Validate(nav);
> > ```
> > 
> > 
> > In your case you will get some errors because of the issues @brianpos mentioned above.
> 
> Thanks Marco,
> Which import is required for `var validator = new Validator();` I have the `https://www.nuget.org/packages/Hl7.FhirPath` installed (version 1.3.0)

You need `https://www.nuget.org/packages/Hl7.Fhir.Specification.STU3` when you are using Fhir version STU3. If you use R4 you will need `https://www.nuget.org/packages/Hl7.Fhir.Specification.R4`

**Comment by brianpos** [comment]
If you're not sure on things, use the fhirpathtester tool to check your resource and fhirpath expression.
It's in the Windows store, or the release and code is on github too. 
I'm not sure having the Patient in the middle of the fhirpath expression is valid. I'd have to look that up. 
The type name is only valid at the root of the expression, and could be an issue with the fhirpath.js implementation. 
I'll check it over.
If you want to contain to type, you would need a where clause.

**Comment by asharma-carecloud** [comment]
> If you're not sure on things, use the fhirpathtester tool to check your resource and fhirpath expression.
> It's in the Windows store, or the release and code is on github too.
> I'm not sure having the Patient in the middle of the fhirpath expression is valid. I'd have to look that up.
> The type name is only valid at the root of the expression, and could be an issue with the fhirpath.js implementation.
> I'll check it over.
> If you want to contain to type, you would need a where clause.

Thanks Brian,
The where clause is also not working in our case, the `type` name is working with the `https://hl7.github.io/fhirpath.js/` with the above payload and the query.

**Comment by gpabon-carecloud** [comment]
We are still suffering from problems regarding the use of FHIRpath Identifiers in any place but the root element.

Given this small example:
```csharp
using Hl7.Fhir.Model;
using Hl7.FhirPath;
using Hl7.Fhir.ElementModel;

namespace tmp
{
    class Program
    {
        static void Main(string[] args)
        {
            var name = new HumanName();
            name.Text = "John Doe";

            var patient = new Patient();
            patient.Active = true;
            patient.Name.Add(name);


            var bundle = new Bundle();
            bundle.Type = Bundle.BundleType.Document;

            var bundleEntry = new Bundle.EntryComponent();
            bundleEntry.FullUrl = patient.ResourceType.ToString() + patient.Id;
            bundleEntry.Resource = patient;
            bundle.Entry.Add(bundleEntry);

            var nav = bundle.ToTypedElement();
            var result = nav.Select("Bundle.entry.first().resource.is(MessageHeader)");
        }
    }
}
```

Gives the following error: `Unhandled Exception: System.InvalidOperationException: Invocation of 'ofType' failed: Resource type name may only appear at the root of a document`.

That is valid FHIRpath, as is the **bdl-12** rule that handles message Bundles: `type = 'message' implies entry.first().resource.is(MessageHeader)` (https://www.hl7.org/fhir/bundle-definitions.html)

Same error is thrown on this query: `Bundle.entry.first().resource.MessageHeader` which seems like a valid FHIRpath expression too (Identifiers are not limited to the beginning of the query in the spec).

We have a somewhat big library of FHIRpath expressions that are valid according to hl7's FHIRpath checker (https://hl7.github.io/fhirpath.js/), and they rely on having identifiers at any position of the query.

**Comment by marcovisserFurore** [comment]
Which version of the Fhir Api are you using? I used the latest release (version 1.4.0) and I've tried your example: `Bundle.entry.first().resource.is(MessageHeader)` and I got no errors (I used the Scalar() function here to get a single result):

```
            /* creating the bundle */
            bundle.Entry.Add(bundleEntry);
            var nav = bundle.ToTypedElement();

            var result = nav.Scalar("Bundle.entry.first().resource.is(MessageHeader)");
            Assert.AreEqual(false, result);
```` 

The following results is `true` (the first resource in the bundle is a Patient:
```
            /* creating the bundle */
            bundle.Entry.Add(bundleEntry);
            var nav = bundle.ToTypedElement();

            var result = nav.Scalar("Bundle.entry.first().resource.is(Patient)");
            Assert.AreEqual(true, result);
```` 


The expression `Bundle.entry.first().resource.MessageHeader` fails, because Resource types may only appear at the root of a document.

**Comment by marcovisserFurore** [comment]
Issue has been answered; I will close the issue
