### ISSUE TITLE
[Validator] bug on slice validation based on valueset binding binding in combination with fixed slice

### ISSUE THREAD

**Issue by ArdonToonstra** [FirelyTeam/fhir-net-api#1147]
Continued from #1070.

The validator is not capable of handling slicing that consists of valueset binding and slices with fixed values. 

[Valueset binding - FAILS 01 - fixed slice and valueset.zip](https://github.com/FirelyTeam/fhir-net-api/files/3717756/Valueset.binding.-.FAILS.01.-.fixed.slice.and.valueset.zip)

https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Slicing.20and.20value.20sets

**Comment by marcovisserFurore** [comment]
In the example you are Value-slicing on path Medication.code.coding. That means that your elements `Medication.code.coding` should have a binding or a fixedValue. Slice3 does not have these constraints. 

Slice 3 should have something like this:

```
<fixedCodeableConcept>
        <coding>
          <system value="http://loinc.org" />
          <code value="12" />
          <display value="12" />
        </coding>
      </fixedCodeableConcept>
```

**Comment by ArdonToonstra** [comment]
@marcovisserFurore , thnx! That works. 

Closing the issue.

**Comment by ArdonToonstra** [comment]
@marcovisserFurore , unfortunately, the current validator logic is not suitable (for us).  The fixed coding or fixed codeableConcept does not work because we cannot fix coding.display. Our implementers should be able to use translated display values or other values than we specify. The validator will not match a slice that contains a coding.display to the slicing definition, resulting in an error. 

Therefore, we now believe a validator should be smart enough to use the fixed values in the child elements.


Example of my test profile:

`<element id="Observation.category">
<path value="Observation.category"/>
 <slicing>
 <discriminator>
<type value="value"/>
<path value="$this"/>
</discriminator>
<rules value="open"/>
</slicing>
<min value="1"/>
</element>
 <element id="Observation.category:LaboratoryTestResultCode">
<path value="Observation.category"/>
<sliceName value="LaboratoryTestResultCode"/>
<short value="LaboratoryTestResultCode"/>
<min value="1"/>
<max value="1"/>
 <fixedCodeableConcept>
 <coding>
<system value="http://snomed.info/sct"/>
<code value="49581000146104"/>
</coding>
</fixedCodeableConcept>
</element>`

**Comment by ArdonToonstra** [comment]
Continues here: https://github.com/FirelyTeam/fhir-net-api/issues/1185
