### ISSUE TITLE
Class for resources that have identifiers

### ISSUE THREAD

**Issue by jerchap** [FirelyTeam/fhir-net-api#1151]
I've been trying to build logic for resolving resources in a bundle from ResourceReferences.

The guidelines for resolving references state:

> Note, in addition, that a reference may be by identifier, and if it is, and there is no URL, it may be resolved by scanning the ids in the bundle.

I have found that each type of resource (Class) implements their own Identifiers properties.  If there was a class or interface that all resources that had an Identifier property could inherit from or implement, it would be possible to write a generalized function that could resolve references by identifier for resources that had identifiers.

Would it be possible for all classes that have an Identifiers property that is of type List<Identifier> to implement an interface with that property or inherit from a common class that has the property?

**Comment by marcovisserFurore** [comment]
Hi @jerchap ,

Thank you for your question and interest in the Fhir .Net Api.

There is no planning to create a Identifier property on each class. 
But you can check on each Resource if there is a property `Identifier` defined by looking into the  NamedChildren collection. I have made an example extension method for this:

``` 
        public static bool HasIdentifier(this Resource resource)
        {
            var found = resource?.NamedChildren.Any(nc => nc.ElementName == "Identifier");

            return found ?? false;
        }
```

Maybe it gives you inspiration to create your own extension method.

**Comment by brianpos** [comment]
Or use the fhirpath engine to check for the value.
In act that could work for all cases.

**Comment by marcovisserFurore** [comment]
I will close this issue, because it has been answered
