### ISSUE TITLE
Cannot load projects from Repo developer-r4 repo

### ISSUE THREAD

**Issue by safr0** [FirelyTeam/fhir-net-api#1157]
Hi, 

I'm using VS2019, I've tried to load solution after downloading the code but somehow all the projects under Common folder are not loading as seen in solution explorer. 

This fails, my is failing my builds. What could be the reason for this, thanks.

**Comment by marcovisserFurore** [comment]
Hi, we are using git submodules, so you should also init those submodules. See our [Wiki page](https://github.com/FirelyTeam/fhir-net-api/wiki/Clone-this-repository-with-submodule-common) how to clone our repository.
