### ISSUE TITLE
Use of HttpWebRequest instead of HttpClient for FHIR Client

### ISSUE THREAD

**Issue by ps-astangl** [FirelyTeam/fhir-net-api#1161]
Why does the FHIR client use HttpWebRequest to perform REST operations for the FHIR client instead of taking an Httpclient. It is by Microsoft [recommended](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest?view=netcore-3.0) to use an HttpClient for new development. 

Is there a specific reason why this design was chosen? Is there a performance gain, better control over disposal, etc? Before implementing this client I was curious about the design choice for its underlying methods.

Thank you.

**Comment by brianpos** [comment]
This has been in there for 5 years, and across the many platforms (net4.0, net4. 5, PCL, netstandard) 
We are working towards a new version of the fhir client that uses the httpclient, however this will be a breaking change for everyone as there are a few very commonly used event handlers that expose it.

**Comment by marcovisserFurore** [comment]
Like @brianpos  stated, we are working on a new  FhirClient (see [here](https://github.com/FirelyTeam/fhir-net-api/pull/1120) a pull request about it). This new FhirClient is on the long term planning board, and that is going to be at least 2020 before it will be released.

**Comment by mmsmits** [comment]
We have added the "new" FhirClient based on HttpClient to develop. This will be released this summer as part of version 2.0
