### ISSUE TITLE
There is a mismatch between Hl7.Fhir.STU3.Core (version 0.93.4.0) and Simplifier / zibs.nl

### ISSUE THREAD

**Issue by Zamolxis666** [FirelyTeam/fhir-net-api#1166]
Hello,
We have to populate an Observation model in accordance to Simplifer (https://simplifier.net/nictizstu3-zib2017/zib-laboratorytestresult-observation).
But for the status property, Simplifier specifies a list of possible codes (see https://simplifier.net/NictizSTU3-Zib2017/216840111388324311604021318--20171231000000) while the ObservationStatus enum from Hl7.Fhir.STU3.Core has the following values: _Registered, Preliminary, Final, Amended, Corrected, Cancelled, EnteredInError, Unknown_. 
As you can see, _Pending_ is not one of them. Moreover, checking https://zibs.nl/wiki/LaboratoryTestResult-v4.1(2017EN)#ResultStatusCodelist you can see that the codes mentioned by Simplifier are the same with the codes mentioned by zibs.nl.

**Comment by marcovisserFurore** [comment]
Hi,

I see in the StructureDefinition that the status of the Observation is extended with the valueset `ResultStatusCodelist`. 

So you have to extend the Status element, like this:
```
  var obs = new Observation();
  obs.StatusElement.AddExtension(
         "http://nictiz.nl/fhir/StructureDefinition/code-specification",
         new CodeableConcept("2.16.840.1.113883.2.4.3.11.60.40.4.16.1", "pending")
  );
```

You say also that you are using version 0.93.4.0 of the Api, which is very old (released in May 17, 2017). I strongly advise you to upgrade to the latest version (1.4.0).

**Comment by Zamolxis666** [comment]
@marcovisserFurore Thank you for your response, I will try
