### ISSUE TITLE
Snapshot generator does not auto-generate referenced snapshots it depends on in 1.4.0

### ISSUE THREAD

**Issue by abelenthoven** [FirelyTeam/fhir-net-api#1168]
In 1.4.0 the functionality of automatically generating Snapshots for **referenced** (so, 1 level deep) StructureDefinitions seems to have changed compared to 1.3.0. Using:

new SnapshotGeneratorSettings()
            {
                ForceRegenerateSnapshots = true,
                GenerateAnnotationsOnConstraints = false,
                GenerateElementIds = false,
                GenerateExtensionsOnConstraints = false,
                GenerateSnapshotForExternalProfiles = true
            };

and a SnapShotResolver which uses the DB-resolver as its externalResolver, the referenced StructureDefinitions are fetched but their Snapshot property is not automatically populated, as seen when debugging after receiving the following message:

"Internal logic failure: Cannot walk into unknown StructureDefinition with canonical 'http://fhir.nl/fhir/StructureDefinition/nl-core-preferred-pharmacy' at 'http://fhir.nl/fhir/StructureDefinition/nl-core-patient#Patient.extension'"

I saw this after trying both versions (1.3.0 and 1.4.0) with the same code. The mentioned error is only present in 1.4.0

**Comment by marcovisserFurore** [comment]
@gstoian . can you made an unittest to prove this?

So a StructureDefinition A that references another StructureDefinition B, By generating a snapshot for A, there must be also a snapshot for B, when `GenerateSnapshotForExternalProfiles = true`

**Comment by marcovisserFurore** [comment]
I've seen your PR. Does this mean that the original code was not able to generate a snapshot for referenced profile?

**Comment by gstoian** [comment]
Yes, it didn't generate it.
