### ISSUE TITLE
Setting Code properties is slow

### ISSUE THREAD

**Issue by michelemottini** [FirelyTeam/fhir-net-api#1169]
Around 100 times slower than setting properties of other types.

The issue is that setting a Code property calls ReflectionHelper.GetAttributeOnEnum() (via EnumUtility.GetLiteral()) - that does various reflection operations that are slow compared to a straight property set.

Probably a better way would be to cache the result of GetAttributeOnEnum() or of GetLiteral()

**Comment by marcovisserFurore** [comment]
See also [this](https://chat.fhir.org/#narrow/stream/179171-dotnet/topic/Setting.20Code.20properties.20is.20slow) discussion on Zulip.

@michelemottini also timed this:

```
   var patient = new Hl7.Fhir.Model.DSTU2.Patient();
   var watch = Stopwatch.StartNew();
   const int count = 10_000;
   for ( var i = 0; i < count; i++ )
   {
      patient.Gender = Hl7.Fhir.Model.AdministrativeGender.Female;
   }
   watch.Stop();
   Console.WriteLine( "Set code X {0:N0}: {1:N1} msec", count, watch.ElapsedMilliseconds );
``` 

Output: Set code X 10,000: 62.0 msec
(for non-code properties the time is < 1 msec)

**Comment by brianpos** [comment]
@michelemottini, any suggestions?

**Comment by michelemottini** [comment]
Cache the enum -> string maps

**Comment by marcovisserFurore** [comment]
This PR has been pulled for `develop-1.x` and `develop`
