### ISSUE TITLE
Xml serialization does not trim whitespace

### ISSUE THREAD

**Issue by michelemottini** [FirelyTeam/fhir-net-api#1176]
Serializing 

```CSharp
new FhirModel2.Patient
{
    Name = new List<FhirModel2.HumanName>
    {
        new FhirModel2.HumanName { Family = new[] { " Smith\r\n\t" } }
    }
}
```

Produces:

```XML
<Patient xmlns="http://hl7.org/fhir">
      <name>
        <family value=" Smith&#xD;&#xA;&#x9;" />
      </name>
 </Patient>
```

Instead of 

```XML
<Patient xmlns="http://hl7.org/fhir">
      <name>
        <family value="Smith" />
      </name>
 </Patient>
```

**Comment by marcovisserFurore** [comment]
@michelemottini , I think you are referring to the following rule on http://hl7.org/fhir/xml.html:

> Implementers SHOULD trim leading and trailing whitespace before writing and SHOULD trim leading and trailing whitespace when reading attribute values (for XML schema conformance)

That looks clear to me, so I will file this as a bug..
