### ISSUE TITLE
Fhir API c# Smart authentication on Azure fhir server

### ISSUE THREAD

**Issue by bobosette** [FirelyTeam/fhir-net-api#1180]
Hi everybody. I setted up an Azure Fhir Server with Smart for Fhir authentication, following this guide https://docs.microsoft.com/en-us/azure/healthcare-apis/use-smart-on-fhir-proxy . Now I have a web app with Visual Studio and I'm using this API to working on the DB with c#.
How can I obtain the access token with my web app? I didn't find any guide about this using c#.
With this code:
FhirClient validationFhirClient = new FhirClient("https://nuwbb.azurewebsites.net");
            validationFhirClient.OnBeforeRequest += (object sender, BeforeRequestEventArgs e) =>
            {
                // Replace with a valid bearer token for this server
                e.RawRequest.Headers.Add("Authorization", "Bearer XXXXXXX");
            };

I can add the token to any call, but before i had to get it, for every call, how can I handle the authorization request without going through the microsoft login online web page?

Thank u

**Comment by mbaltus** [comment]
Hi! You will need to add an extra layer to your application that allows the user to login, so you can obtain the token. Then you don't need to obtain a token and go through the login for every request anymore, just once at the start, or again when the token has expired.

On the page to setup the proxy, Microsoft has also provided a link to an example app, see: https://docs.microsoft.com/en-us/azure/healthcare-apis/use-smart-on-fhir-proxy#download-smart-launch-application. The project is an open source .Net solution, and the app itself is in the fhir-server/samples/apps/SmartLauncher subfolder. You can take a look at that to see how they obtain a token. Once you have it, as you said, you can use that in the FhirClient.

**Comment by marcovisserFurore** [comment]
This issue has been answered. I will close the issue.
