### ISSUE TITLE
Ignore FHIR-version specific profile

### ISSUE THREAD

**Issue by vadi2** [FirelyTeam/fhir-net-api#1184]
The .NET validator currently chokes on this: https://www.hl7.org/fhir/versioning.html#mp-version by saying "Incomplete : Unable to resolve reference to profile 'http://hl7.org/fhir/3.0/StructureDefinition/Bundle'"

In practice it just needs to ignore this kind of `meta.profile` entry because it is only used to specify the FHIR version.

**Comment by ewoutkramer** [comment]
Yes.  Let's continue this discussion under #1258 or #1429.
