### ISSUE TITLE
[Validator] should check for fixed, pattern or binding values when discriminator type is 'value' or 'pattern' 

### ISSUE THREAD

**Issue by ArdonToonstra** [FirelyTeam/fhir-net-api#1185]
Continued from issue #1070 and #1147.

The validator should look at fixed, pattern and binding when discriminator type is value or pattern. This means there will be no difference between the two mentioned types. This enhancement should also be available for STU3. Attached to this issue is a zip file containing test cases.

References:

> If the type is value, or pattern, then the element definition must use either:
> 
> ElementDefinition.fixed[x], or
> ElementDefinition.pattern[x], or
> if the element has a terminology binding, a required binding with a Value Set that enumerates the list of possible codes in the value set ("extensional definition")

http://hl7.org/fhir/profiling.html#discriminator

- https://chat.fhir.org/#narrow/stream/179280-fhir.2Finfrastructure-wg/topic/Is.20there.20a.20difference.20between.20value.20or.20pattern.20slicing.3F
- https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Slicing.20and.20value.20sets
- https://chat.fhir.org/#narrow/stream/179181-netherlands/topic/Validation.20of.20MedMij.20example

[validator-discriminator-type.zip](https://github.com/FirelyTeam/fhir-net-api/files/3932258/validator-discriminator-type.zip)

**Comment by ewoutkramer** [comment]
See also #1246.
