### ISSUE TITLE
Installing NuGet package in Xamarin.iOS projects causes build to fail

### ISSUE THREAD

**Issue by phil-harmoniq** [FirelyTeam/fhir-net-api#1186]
The full error message given:

`Multiple assemblies with equivalent identity have been imported: 'C:\Users\phil\.nuget\packages\system.reflection.emit\4.3.0\ref\netstandard1.1\System.Reflection.Emit.dll' and 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.Reflection.Emit.dll'. Remove one of the duplicate references.`

[I've created a repo so you can try for yourself.](https://github.com/phil-harmoniq/fhir-xamarin-ios-bug) It's the default Xamarin.iOS template with the only change made is installing the `Hl7.Fhir.STU3` package. I'm also unsure why it seems to be referencing `netstandard1.1` when there is `netstandard2.0` compatibility in the STU3 package.

**Comment by mbaltus** [comment]
Hi Phil,

I've downloaded your project, and built it. The error message you get does not appear for me, and the build succeeds. Could you try and clean up your .nuget folder, to see if that helps at all?

**Comment by ewoutkramer** [comment]
closed because of inactivity
