### ISSUE TITLE
deriveInstanceType should consider XmlRepresentation.TypeAttr

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/fhir-net-api#1191]
When deriving an instance type in a logical model of an element where ElementDefinition.representation = TypeAttr, TypedElementOnSourceNode should take this xsi:type annotation in the instance into consideration. This is especially needed when using the CCDA on FHIR logical models.

**Comment by alexzautke** [comment]
Open issue: "xsi:type" is not recognized as a special attribute, it needs to be manually added to the StrcutureDefinition as a separate element.

**Comment by ewoutkramer** [comment]
I see there is code that looks for this type attribute to derive the instance type - so that seems to work. I agree this seems to be built in as a special "hard coded" case, so the API does not really recognize the attribute - and will also represent this as a "normal" child on the ITypedElement.
