### ISSUE TITLE
Make TypedElementOnSourceNode support other type models besides FHIR

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/fhir-net-api#1193]
tryMapFhirPrimitiveTypeToSystemType in TypedElementOnSourceNode is currently hard-coded to FHIR. When needing to support different type systems (like CCDA), TypedElementOnSourceNode needs to be made more flexible in order to allow custom type -> TypeSpecifier mappings.

**Comment by brianpos** [comment]
I've added stuff to this for my own use in some cases. So I believe it's possible (not just in my fork)
