### ISSUE TITLE
ModelState is invalid - Questionnaire purpose

### ISSUE THREAD

**Issue by mattkoch614** [FirelyTeam/fhir-net-api#1205]
I have a controller method that is attempting to run model binding validation on a Questionnaire (json) being passed in via a POST request. 

The Questionnaire JSON representation is simple, and model validation consistently fails when it tries to deal with the ``purpose`` attribute:

```json
{
	"resourceType": "Questionnaire",
	"id": "1",
	"identifier": [
		{
			"system": "https://system.abcde.org/",
			"value": "MED-1234"

		}
	],
	"name": "teststudy123",
	"title": "Important Document",
	"status": "draft",
	"subjectType": [
		"ResearchStudy"
	],
	"purpose": "Part A",
	"item": [
		{
			"linkId": "1"
			//omitted for brevity
		}
	]
}
```

Here's a snippet from the Controller method:

```csharp
        [Route("")]
        [HttpPost]
        public async Task<IHttpActionResult> store([FromBody] Questionnaire request)
        {
            if (!ModelState.IsValid)
            return BadRequest(ModelState);
            //...
        }
```

It seems that using a simple string for "Purpose" fails because it can't convert it to "Hl7.Fhir.Model.Markdown" but the FHIR spec indicates that string representations should be valid (for Markdown data types.):

```
Exception = {"Error converting value \"Part A\" to type 'Hl7.Fhir.Model.Markdown'. Path 'purpose', line 17, position 33."}

InnerException = {"Could not cast or convert from System.String to Hl7.Fhir.Model.Markdown."}
```

**Comment by brianpos** [comment]
I'd check the version of the fhir libs that you're using, that might cause issues there, also consider the http://github.com/brianpos/fhir-net-web-api facade project that does all the interface bindings, and let's you worry about the actual functionality you want to handle.
Also handles xml and json without extra code on your side. 
Theres a demo in there showing a server that uses the file system for storage.

**Comment by mattkoch614** [comment]
Thanks @brianpos. We got around this by accepting a ``JObject`` as a parameter in the Controller method instead of a strongly typed Questionnaire, and then just parsing the text representation of that into a Questionnaire. This works for our use case.

**Comment by marcovisserFurore** [comment]
The question has been answered. I close this issue.
