### ISSUE TITLE
FhirClient.SearchUsingPost() using multiple includes throws exception

### ISSUE THREAD

**Issue by ChrisLurge** [FirelyTeam/fhir-net-api#1206]
When adding more than one includes to the SearchParameter, the SearchUsingPost-Method
throws the exception: 'An item with the same key has already been added.', whereas the Search-Method
works fine. Also using the overloaded method, passing a string-array for the includes, failes
if the array contains more than one element.

Sample code:

` 
            var sp = new SearchParams();
            sp.Parameters.Add(new Tuple<string, string>("_id", "8465,8479"));
            sp.Include.Add("subject");

            client.Search<Procedure>(sp);
            // OK
            client.SearchUsingPost<Procedure>(sp);
            // OK

            // Add a further include
            sp.Include.Add("encounter");
            client.Search<Procedure>(sp);
            // OK

            client.SearchUsingPost<Procedure>(sp);
            // Exception! 'An item with the same key has already been added.'
`

I can't see an error in my code.

**Comment by marcovisserFurore** [comment]
Thanks @ChrisLurge. This is indeed a bug. We use somewhere a dictionary for the parameters, which dictates that the parameters should be unique. Which should be the case. We will solve this.

Thanks for your feedback.

**Comment by marcovisserFurore** [comment]
To the developer:
In `EntryToHttpExtensions.setBodyAndContentType` we use a Dictionary (bodyParameters) for building the parameterlist. This should be something that implements `IEnumerable<KeyValuePair<string, string>>`
