### ISSUE TITLE
Recognising xHtml within an instance is hardcoded to FHIR

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/fhir-net-api#1208]
In XObjectFhirXmlExtensions it's hard-coded how / if a SourceNode should be created for xHtml elements. However it is currently limited to the FHIR representation of xHtml (it expects that there is always a XHTML namespace given). However that might not always be true for instances of logical models (CCDA on FHIR for example). Type information would normally be needed for this check.

**Comment by ewoutkramer** [comment]
As SourceNode has no type information, that's pretty much impossible :-(    So, maybe, this decision is not up to the SourceNode, but (as you have implemented it now), to be handled at a higher level.

The current solution for reading CDA files assumes the SourceNode can put narrative into nodes, which is then combined into a single node by the TypedElementOnSourceNode class. However, mixed-content narrative cannot be so easily translated 1-on-1 to SourceNodes, and so we do not currently handle mixed-context narrative correctly.

**Comment by ewoutkramer** [comment]
See also #1274.
