### ISSUE TITLE
Parsing _text attribute on a questionnaire

### ISSUE THREAD

**Issue by mattkoch614** [FirelyTeam/fhir-net-api#1217]
I am trying to parse a JSON representation of a Questionnaire using the JSON parser. Parsing succeeds with no errors, but it seems I'm not able to properly parse the primitive ``_text`` property of my JSON. The JSON below uses an extension on ``item`` text to indicate it should be rendered using XHTML. When parsed, item text is ``null`` in the Questionnaire:

**Snippet:**
```json
{
	"resourceType": "Questionnaire",
	"id": "1",
	"identifier": [
		{
			"system": "http://testsystem",
			"value": "12345"
		}
	],
	"meta": {
		"lastUpdated": "2018-02-07T13:28:17.239+05:00",
		"versionId": "TESTVERSION123"
	},
	"name": "questionnaire_test",
	"title": "Important Questionnaire",
	"status": "draft",
	"subjectType": [
		"Patient"
	],
	"publisher": "johndoe",
        "item": [
        {
            "linkId": "2",
            "prefix": "0",
            "type": "display",
            "_text": {
                "extension": [
                    {
                        "url": "http://hl7.org/fhir/StructureDefinition/rendering-xhtml",
                        "valueString": "<p>What risks can I expect from taking part in this study?</p>"
                    }
                ]
            }
        }
     ]
}
```

Anything I'm doing wrong? Is the JSON to blame or something I may be doing wrong with the parser? In this case, there is no other representation of the text *other than* the XHTML form in the extension, so having a regular "text" field didn't seem appropriate.

**Comment by brianpos** [comment]
That resource definition looks fine to me.
I used the fhirpath tester to convert it to XML and read the property and it works fine. 
(it uses the fhir client serializers)
```
<Questionnaire xmlns="http://hl7.org/fhir">
  <id value="1" />
  <meta>
    <versionId value="TESTVERSION123" />
    <lastUpdated value="2018-02-07T13:28:17.239+05:00" />
  </meta>
  <identifier>
    <system value="testsystem" />
    <value value="12345" />
  </identifier>
  <name value="questionnaire_test" />
  <title value="Important Questionnaire" />
  <status value="draft" />
  <publisher value="johndoe" />
  <subjectType value="Patient" />
  <item>
    <linkId value="1" />
    <prefix value="0" />
    <text>
      <extension url="http://hl7.org/fhir/StructureDefinition/rendering-xhtml">
        <valueString value="What risks can I expect from taking part in this study?" />
      </extension>
    </text>
  </item>
</Questionnaire>
```

**Comment by mattkoch614** [comment]
Could it be that I added the extension on the `_text` field and not the `text` field? Strange how it’s not reading the property for me.

**Comment by brianpos** [comment]
Not likely, the _text is how json extensions are represented.
Maybe share your code that is parsing, reading the content.

**Comment by mattkoch614** [comment]
Interesting, `TextElement` appears to actually have extension data on it, even though in the debugger (in Visual Studio) it looked null to me. 

Test repo:
https://github.com/mattkoch614/FhirTester

I think we're good here. Closing - thanks @brianpos
