### ISSUE TITLE
[Validator] incorrectly triggers eld-16 error using FHIR 3.0.2 

### ISSUE THREAD

**Issue by ArdonToonstra** [FirelyTeam/fhir-net-api#1219]
Validating StructureDefinitions on Simplifier (now based on 1.4 of the API) gives false eld-16 warnings when validating against FHIR 3.0.2. It does not when you validate against 3.0.1. 

Easily reproducible through simplifier.net/validate with any structuredefinition.

The eld-16 constraint is untouched in the two versions:

3.0.2 - 
https://simplifier.net/packages/hl7.fhir.r3.core/3.0.2/files/62015/~xml 
--------------
<constraint>
                <key value="eld-16" />
                <severity value="error" />
                <human value="sliceName must be composed of proper tokens separated by "/"" />
                <expression value="sliceName.empty() or sliceName.matches('^[a-zA-Z0-9\\/\\-\\_]+$')" />
                <xpath value="not(exists(f:sliceName/@value)) or matches(f:sliceName/@value, '^[a-zA-Z0-9\\/\\-\\_]+$')" />
            </constraint>
                                    
                                    
3.0.1. - https://simplifier.net/packages/simplifier.core.stu3.datatypes/3.0.1/files/113/~xml 
--------------

<constraint>
                <key value="eld-16" />
                <severity value="error" />
                <human value="sliceName must be composed of proper tokens separated by "/"" />
                <expression value="sliceName.empty() or sliceName.matches('^[a-zA-Z0-9\\/\\-\\_]+$')" />
                <xpath value="not(exists(f:sliceName/@value)) or matches(f:sliceName/@value, '^[a-zA-Z0-9\\/\\-\\_]+$')" />
            </constraint>

**Comment by wardweistra** [comment]
Same when doing validate on https://simplifier.net/acmebaseprofiles/acmebasepatient (which also depends on FHIR 3.0.2 package, which indeed is not expected to work with 1.4 API)

**Comment by wardweistra** [comment]
Ardon looked up whether there was any difference in eld-16 between the 3.0.1 and 3.0.2 package of the core, but there wasn't:
3.0.2 - 
https://simplifier.net/packages/hl7.fhir.r3.core/3.0.2/files/62015/~xml 
--------------
<constraint>
                <key value="eld-16" />
                <severity value="error" />
                <human value="sliceName must be composed of proper tokens separated by "/"" />
                <expression value="sliceName.empty() or sliceName.matches('^[a-zA-Z0-9\\/\\-\\_]+$')" />
                <xpath value="not(exists(f:sliceName/@value)) or matches(f:sliceName/@value, '^[a-zA-Z0-9\\/\\-\\_]+$')" />
            </constraint>
                                    
                                    
3.0.1. - https://simplifier.net/packages/simplifier.core.stu3.datatypes/3.0.1/files/113/~xml 
--------------

<constraint>
                <key value="eld-16" />
                <severity value="error" />
                <human value="sliceName must be composed of proper tokens separated by "/"" />
                <expression value="sliceName.empty() or sliceName.matches('^[a-zA-Z0-9\\/\\-\\_]+$')" />
                <xpath value="not(exists(f:sliceName/@value)) or matches(f:sliceName/@value, '^[a-zA-Z0-9\\/\\-\\_]+$')" />
            </constraint>

**Comment by marcovisserFurore** [comment]
This is an error in the FHIR standard. The double backslashes are incorrect here. In the fhir-net-api we correct this error ourselves, but you use the Fhir packages which contains still this error. It has been solved in FHIR standard 4.0.1, but unfortunately not in FHIR standard 3.0.2.

This was reported in august 2017, but unfortunately not solved for STU3. See the original ticket here: https://jira.hl7.org/browse/FHIR-13771
