### ISSUE TITLE
[validator 1.4] When namespace xmlns="http://hl7.org/fhir" is not present, the error is still unclear

### ISSUE THREAD

**Issue by furoreSebastiaan** [FirelyTeam/fhir-net-api#1220]
[unclear_error.zip](https://github.com/FirelyTeam/fhir-net-api/files/4064858/unclear_error.zip)

check xml in zip, when you validate it, the error message is unclear. Not fixed in 1.4

**Comment by ArdonToonstra** [comment]
Not fixed in 1.6 as well.

![image](https://user-images.githubusercontent.com/20518398/78689435-9e385000-78f6-11ea-8c3a-90bf40043ff0.png)
