### ISSUE TITLE
How to i convert from a resource type string to a ResourceType enum?

### ISSUE THREAD

**Issue by jerchap** [FirelyTeam/fhir-net-api#1226]
I'm assuming I can't just do an Enum.Parse...

**Comment by brianpos** [comment]
.GetLiteral()
(its an extension method, can't remember where)

**Comment by brianpos** [comment]
Or is this what you're looking for?
var patientEnumTypeValue = ModelInfo.FhirTypeNameToFhirType("Patient");

**Comment by jerchap** [comment]
ModelInfo.FhirTypeNameToResourceType,  that's the one.  thanks for pointing me in the right direction.  What is the difference between FHIRAllTypes and ResourceType?  Is ResourceType a subset of FhirAllTypes?

**Comment by marcovisserFurore** [comment]
The enum `FHIRAllTypes` include all Resourcetypes, datatypes, abstract classes. The enum `ResourceType` is a collection of only the Resourcetypes, like Patient, Appointment, Observation, etc. So indeed is ResourceType a subset of FHIRAllTypes
