### ISSUE TITLE
operation definitions

### ISSUE THREAD

**Issue by jerchap** [FirelyTeam/fhir-net-api#1228]
I have found a number of operations defined in Hl7.Fhir.Rest.RestOperation, but not all.

the [Fhir operstions list](https://www.hl7.org/fhir/operationslist.html) also describes $convert, $graphql, $apply, $data-requirements, $subset, $implements, $conforms, $versions, $submit, $subsumes, $find-matches, $document, $closure, , $find, $evaluate-measure, $care-gaps, $process-message, $preferred-id, $stats, $lastn, $match, and $snapshot.  Are these defined somewhere else in the api?

**Comment by marcovisserFurore** [comment]
Hi,

You can use the following methods of the api:

```
public Resource WholeSystemOperation(string operationName, Parameters parameters = null, bool useGet = false)

public Resource TypeOperation<TResource>(string operationName, Parameters parameters = null,
            bool useGet = false) where TResource : Resource

public Resource InstanceOperation(Uri location, string operationName, Parameters parameters = null, bool useGet = false)
```

For example the operation `$everything`:

```
var client = new FhirClient(testEndpoint);
            var start = new FhirDateTime(2014,11,1);
            var end = new FhirDateTime(2015,1,1);
            var par = new Parameters().Add("start", start).Add("end", end);
            var bundle = (Bundle)client.InstanceOperation(ResourceIdentity.Build("Patient", "example"), "everything", par);
```
