### ISSUE TITLE
Parser does not distiguish between date and dateTime FHIR types

### ISSUE THREAD

**Issue by wburgers** [FirelyTeam/fhir-net-api#123]
Hi,

.Net does not have a date type, so everything is a dateTime.
But the FHIR specification shows that a date type should not include a time.
https://www.hl7.org/fhir/datatypes.html#date
Would it be possible to chop off the time if specified in a serialized resource?
For example when constructing the .Net FHIR model.

Let me know.

Best regards,
Willem

**Comment by brianpos** [comment]
So if a component included a time property, then strip it off as it reads or writes it?

**Comment by wburgers** [comment]
Yeah that's right, unless I'm not seeing an obvious downside, I think it is good to be more strict right?

**Comment by brianpos** [comment]
The obvious downside would be that timezones might mess with things here, and some of the code in here converts things to UTC, which could change the date with some values.
Not using the DateTime for Date properties would not have any of these issues.

Any objections to this one being closed?

**Comment by marcovisserFurore** [comment]
No objections ;)
