### ISSUE TITLE
Possible bug in snapshot generator

### ISSUE THREAD

**Issue by Gjoll** [FirelyTeam/fhir-net-api#1232]
In the StructureDefinition.differential is it required that each element have the Type
explicitly defined even if the type is unchanged from the base element.

If the answer is yes (type required), then the mistake is mine.

If not ...

If I run the c# snapshot generator in a profile with an element define in the differential
that does not have the type explicitly defined in the differential, I get type set to _code values
as below. If I set Type explicitly then all is fine.

Is this a bug or a feature :-)

-- Input --
{
"id": "Extension.extension:landMark.url",
"path": "Extension.extension.url",
"fixedUrl": "landMark"
}

    output --

"type": [
{
"_code": {
"extension": [
{
"url": "http://hl7.org/fhir/StructureDefinition/structuredefinition-json-type",
"valueString": "string"
},
{
"url": "http://hl7.org/fhir/StructureDefinition/structuredefinition-xml-type",
"valueString": "xsd:string"
},
{
"url": "http://hl7.org/fhir/StructureDefinition/structuredefinition-rdf-type",
"valueString": "xsd:string"
},
}

**Comment by ewoutkramer** [comment]
This seems correct.  This is indeed the type of the `.id` element. This is not a normal element with a normal FHIR type (this element, together with `value` for the primitives and the `id` element are the exceptions). They are at the bottom of the type hierarchy, and so they are not anymore of a "fhir type" (which is coded) but with these extensions - to mark the fact that they are really primitives.  Unless I am overlooking something, it seems the snapshot generator is doing this exactly: you leave out the type of `.url`, and it adds these special extensions in the snapshot.

**Comment by Gjoll** [comment]
OK. Guess I didn't understand that .id was handled differently. Thanks for the response!
Hope you all are virus free!
