### ISSUE TITLE
Think about removing SimpleQuantity as datatype

### ISSUE THREAD

**Issue by mmsmits** [FirelyTeam/fhir-net-api#1240]
Since SimpleQuantity is not a datatype, but a profile, I think we should consider removing it from our code. This being a breaking change I suggest we do this for 2.0

See #999 for some issues it will solve

**Comment by ewoutkramer** [comment]
Agree. We need to do this.

**Comment by ewoutkramer** [comment]
And MoneyQuantity too.

**Comment by ewoutkramer** [comment]
This has been removed in 2.0 of the API.
