### ISSUE TITLE
Custom profile conformance testing

### ISSUE THREAD

**Issue by dattachandan** [FirelyTeam/fhir-net-api#1241]
Hi team,

We are trying to test conformance of a custom FHIR resource which has the StructureDefinition in an XML file. How do we test conformance of the custom profile inside your .net API against a Vonk FHIR server?

Also, can we achieve the workflow described below? If not, what would be the best practice to test conformance of a FHIR server with custom profiles?

The steps for the workflow: 
- get a custom Profile IG from someone who might have used SImplifier or any other tool such as Forge for example  [here](http://build.fhir.org/ig/hl7au/au-fhir-pd/downloads.html) 
- import the definition to some tool that can auto-generate the TestScripts from the custom profile definitions 
- running the tests against an implemented Vonk FHIR server with a test runner tool such as Aegis TouchStone UI or the [TestScript Editor](https://touchstone.aegis.net/touchstone/userguide/html/testscript-authoring/testscript-editor.html)

**Comment by mbaltus** [comment]
Hi!
If you upload the profiles and other conformance resources to the administration layer of your Vonk server, and configure the Vonk server to use the custom profiles, Vonk will be capable of validating incoming data against them. See [our Vonk documentation](http://docs.simplifier.net/vonk/features/conformanceresources.html#conformance) for more information. Further Vonk questions can best be asked by emailing us, see the [contact page](http://docs.simplifier.net/vonk/contact.html) for Vonk.

Your workflow seems doable, although I do not know of a tool that can auto-generate TestScript resources from profiles. Please email the Vonk team if you want to elaborate on the kind of conformance testing you want to do.
