### ISSUE TITLE
Helper classes to work with custom StructureDefinition and generation of differentials

### ISSUE THREAD

**Issue by dattachandan** [FirelyTeam/fhir-net-api#1242]
Hi team

Is there a guide on how to use the .net API to create POCOs given a custom profile StructureDefinition XML?

**Comment by mbaltus** [comment]
All resources conforming to a profile will still be FHIR resources, so you can just use the standard POCO's from the library. In your own code, you can create extra checks, for example to validate a POCO against a custom profile after the data has been filled in. Validation methods come with this library.

Here's a nice blog about custom resources and using the FHIR library: https://brianpos.com/2018/05/03/code-generation-fhir-custom-resources/
