### ISSUE TITLE
[Validator] Rename nameReference to contentReference

### ISSUE THREAD

**Issue by ArdonToonstra** [FirelyTeam/fhir-net-api#1272]
We got the following error from the validator.

Exception : Internal logic failure: Invalid StructureDefinition: element misses either a type reference or nameReference at 'http://nictiz.nl/fhir/StructureDefinition/zib-BloodPressure#Observation.component.code'

It took us a while to figure that a nameReference is actually a contentReference is an ElementDefinition.contentReference.

Please rename this so the error code is improved.

**Comment by ArdonToonstra** [comment]
We don't get this erro anymore with the 1.6 release of the API. So this one can be closed.

**Comment by ArdonToonstra** [comment]
Wow, excuse me, We can close issue 1273 instead of this one.

**Comment by ewoutkramer** [comment]
We'll make it say:

"Invalid StructureDefinition: element misses either a type reference or a value in ElementDefinition.contentReference at 'RRRRR.a.b.c'"
