### ISSUE TITLE
Release notes link should lead to the current release notes in README.md

### ISSUE THREAD

**Issue by hannni** [FirelyTeam/fhir-net-api#1285]
Currently there's a link in the README.md to http://docs.simplifier.net/fhirnetapi/releasenotes.html, but it should point to https://github.com/FirelyTeam/fhir-net-api/releases and the text should be changed accordingly.

**Comment by marcovisserFurore** [comment]
Yes, you are right! Thanks for letting us know.  We will change this in the next release.
