### ISSUE TITLE
<a/> can be incorrectly parsed as a Resource

### ISSUE THREAD

**Issue by hannni** [FirelyTeam/fhir-net-api#1286]
`new FhirXmlParser().Parse<Patient>( "<a/>");` incorrectly returns a patient instead of throwing an Exception using Hl7.Fhir.STU3 in Version 1.6.0.

**Comment by marcovisserFurore** [comment]
Default, the permissive parsing is set to true. So parsing is more forgiving. 
When you  switch off permissive parsing, you will receive an Exception (`FormatException`):

```
var patient = new FhirXmlParser(new ParserSettings() { PermissiveParsing = false }).Parse<Patient>("<a/>");
```
