### ISSUE TITLE
[FHIRClient] Check completeness of unit tests

### ISSUE THREAD

**Issue by mmsmits** [FirelyTeam/fhir-net-api#1291]
PR https://github.com/FirelyTeam/fhir-net-api/pull/1120 introduces new unit tests. 
Check if every part of the schema below is being tested.

![image](https://user-images.githubusercontent.com/8956842/76206316-10d0e580-61fc-11ea-92c8-55f45669a75e.png)

**Comment by ewoutkramer** [comment]
@mmsmits included this in the new FhirClient PR.
