### ISSUE TITLE
Model info: wrong target for STU3 DiagnosticReport.encounter parameter 

### ISSUE THREAD

**Issue by michelemottini** [FirelyTeam/fhir-net-api#1298]
It should be just `Encounter` - see 
https://github.com/FirelyTeam/fhir-net-api/blob/develop-1.x/stu3/src/Hl7.Fhir.Core/Model/Generated/Template-ModelInfo.cs#L965

**Comment by michelemottini** [comment]
R4 appears to have the same problem

**Comment by ewoutkramer** [comment]
This PR altered the generated code instead of fixing it in the template or source. We will need to find another solution.

**Comment by ewoutkramer** [comment]
Ok, this turns out to be a mistake in all but one of the 12 resources that declare this search paramter: http://hl7.org/fhir/searchparameter-registry.html#clinical-encounter

Only for DocumentReference (http://hl7.org/fhir/documentreference.html#search) this turns out to need EpisodeOfCare.

**Comment by ewoutkramer** [comment]
Fixed in #1365 - where this issue re-appeared after the template was re-run.
