### ISSUE TITLE
New r5 Specification data has not been stripped of narrative

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/fhir-net-api#1300]
Since 1.6, the xml files profiles-types, profiles-resources, profiles-others contain narrative. Previously, we removed this to both decrease the package size and also save time parsing the structure definitions. Since these files are read often by the validators having the narrative present might present a performance problem.

Note that the FhirXmlParser simply ignores these nodes, but the scanners used in the DirectorySource might not. Also, since xml parsing is done in memory, this will result in a larger memory footprint.

**Comment by ewoutkramer** [comment]
We actually had a build step that did this. Maybe this got lost in the process of moving to Azure Pipelines?

**Comment by ewoutkramer** [comment]
Only a problem in R5 - no hurry since this is still beta.

**Comment by ewoutkramer** [comment]
@marcovisserFurore - I think you recently fixed this?

**Comment by marcovisserFurore** [comment]
This has been fixed now for 2.0. The narratives are removed now during the download phase in the script `DownloadFhirBuildProfile.ps1`
