### ISSUE TITLE
FHIRPath parsing failure while validating the StructureDefinition of StructureDefinition

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/fhir-net-api#1302]
Validating the StructureDefinition of StructureDefinition (FHIR 3.0.2) causes an issue in the compilation of the FHIRPath expression for sdf-8 which has been changed between FHIR 3.0.1 and FHIR 3.0.2.

"Compilation of FhirPath for constraint 'sdf-8' failed: Compilation failed: Parsing failure: unexpected '='; expected ) (Line 1, Column 17); recently consumed: urce.kind"
"Evaluation of FhirPath for constraint 'sdf-8' failed: Object reference not set to an instance of an object."

**Comment by alexzautke** [comment]
Used the following StructureDefinition for it:
https://hl7.org/fhir/STU3/structuredefinition.profile.json

**Comment by marcovisserFurore** [comment]
I also filed an issue at HL7: https://jira.hl7.org/browse/FHIR-26877
