### ISSUE TITLE
R5: ModelInfo.IsCoreModelTypeUri does not acknowledge type URIs in the form 'http://hl7.org/fhirpath/System.String'

### ISSUE THREAD

**Issue by abelenthoven** [FirelyTeam/fhir-net-api#1322]
FHIR core type URI's (like http://hl7.org/fhirpath/System.String) have changed in R5, but are not recognized by the ModelInfo.IsCoreModelTypeUri method as valid FHIR core types

**Comment by ewoutkramer** [comment]
I don't think it needs to - it should recognize the FHIR.* namespaced types (for which there are StructureDefinitions) - these System.String types are "axiomatic", and are defined outside of FHIR - I don't think this function should handle those.

**Comment by ewoutkramer** [comment]
I'll make this clear in the documentation of the function, though.
