### ISSUE TITLE
Add "split" FHIRPath function

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/fhir-net-api#1334]
In the FHIR Mapping language it's not uncommon to encounter mapping rules where a string need to be split given a certain separator. Add a special function to the FHIRPath compiler, although it's not officially specified, to make for example 'a,b,c,d'.split(',') work.

Proposal: Define split as split(separator : String) : collection. Given an empty string, return a collection. Otherwise return a collection of strings which were delimited by the given separator.

**Comment by brianpos** [comment]
While you're doing this you should also add in the Join to do the reverse...
