### ISSUE TITLE
Using C# 8.0

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/fhir-net-api#1335]
According to the documentation only netstandard2.1 is supporting C# 8.0 (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version).

So we should also upgrade to netstandard2.1 (we are now supporting netstandard2.0). We have to check if that does not cause too much problems.

**Comment by ewoutkramer** [comment]
It looks like netstandard 2.1 is supported as well.  We can avoid using the features that require the CLR changes - the most interesting bit is the new attributes that support nullable reference types:

> Nullable reference types make use of several attributes to provide better warnings. Those attributes were added in .NET Core 3.0. Other target frameworks haven't been annotated with any of these attributes. That means nullable warnings may not accurately reflect potential issues.

Might mean we can only trust the output of the netstandard 2.1 warnings, not of the others. But I have not noticed these differences yet (did a small pilot a few weeks ago).

**Comment by ewoutkramer** [comment]
Very good summary with pointers to even more details: https://stackoverflow.com/questions/56651472/does-c-sharp-8-support-the-net-framework (look for Stephen Kennedy's answer).

In short:

> C# 8 will be fully supported on .net core 3.0 and .net standard 2.1 only. If you manually edit the project file to use C# 8 with .net core 2.1, you are in unsupported territory. Some C# 8 features will happen to work well, some C# 8 features will work not too well (e.g. poor performance), some C# 8 features will work with extra hacks, and some C# 8 features will not work at all. Very complex to explain. We do not actively block it so the expert users who can navigate through it can do so. I would not recommend this unsupported mix&match to be used broadly.

(Jan Kotas)

> People like you who are willing understand -- and work around them -- are free to use C# 8. The point is, not all language features will work on down-level targets.

(Immo Landwerth)

**Comment by ewoutkramer** [comment]
Specifically about nullable references: https://github.com/dotnet/runtime/issues/30493
