### ISSUE TITLE
[question] Azure FHIR server

### ISSUE THREAD

**Issue by quicoli** [FirelyTeam/fhir-net-api#1369]
Hello,

this might be a silly question... 
Does fhir-net-api work with Azure FHIR server?

**Comment by ewoutkramer** [comment]
Not a silly question ;-)

If you mean Microsoft's Azure FHIR server, then, yes.  In fact, Microsoft's server is built on top of this API.

**Comment by marcovisserFurore** [comment]
And you can use the `FhirClient` of the `fhir-net-api` to communicate with Microsoft's Azure FHIR server, or any other FHIR server, like Vonk or Hapi.

**Comment by quicoli** [comment]
that's great! thanks!
