### ISSUE TITLE
Snapshot generator: Stop inheriting http://hl7.org/fhir/StructureDefinition/structuredefinition-explicit-type-name extension

### ISSUE THREAD

**Issue by abelenthoven** [FirelyTeam/fhir-net-api#1373]
Some structuredefinition extensions are prevented from being inherited by the snapshot generator, e.g. structuredefinition-normative-version. http://hl7.org/fhir/StructureDefinition/structuredefinition-explicit-type-name needs to be added to that list, at least until there is some mechanism that tells us which extensions should or should not be inherited

**Comment by wardweistra** [comment]
The request for a non-hardcoded way is captured here: https://jira.hl7.org/browse/FHIR-27535

**Comment by abelenthoven** [comment]
Sorry I was mistaken :)
