### ISSUE TITLE
fhir-net-api-release-1.7.0-r4 missing Hl7.Fhir.Utility reference

### ISSUE THREAD

**Issue by emoryDossmannSCP** [FirelyTeam/fhir-net-api#1386]
Many references to Hl7.Fhir.Utility library in package however it does not exist.

**Comment by ewoutkramer** [comment]
Do you have a bit more details for us?  This github repo is compiled and run daily by many - and is also run through an CI build and unit-test engine before every PR. So, this might be a problem local to your machine, however we need a bit more information before we can help you with that.

**Comment by ewoutkramer** [comment]
Hearing no response, I am closing this issue.
