### ISSUE TITLE
Unable to find project

### ISSUE THREAD

**Issue by ricktiger** [FirelyTeam/fhir-net-api#1387]
I downloaded fhir-net-api-1.6.0-r4.zip from Git and tried to build the solution in VS 2019 and I get lots of the same error...
Unable to find project 'C:\Users\XXX\Documents\Visual Studio 2017\Projects\HI7.FHIR\1.6.0 for R4 (released 20200304)\fhir-net-api-1.6.0-r4\common\src\Hl7.FhirPath\Hl7.FhirPath.csproj'

Can someone please advise? Thank you!

**Comment by ewoutkramer** [comment]
This project has a submodule - it depends on another github repo (https://github.com/FirelyTeam/fhir-net-common).  If you use git to clone this repo, you'll almost automatically get that project pulled in too - this is not the case when you use zip files.  So, you'll have to manually download the zip from the `fhir-net-common` project and then make sure it's contents end up in the `common` directory.
