### ISSUE TITLE
Invariant(fhirpath expression) doesn't evaluate properly

### ISSUE THREAD

**Issue by MatthijsvdWielen** [FirelyTeam/fhir-net-api#1389]
The expression is: Bundle.entry.descendants().reference.distinct().subsetOf(Bundle.entry.fullUrl)

For the current Example instance, the invariant should evaluate to true, which it does, when I check it with the FHIRPath Demo(https://hl7.github.io/fhirpath.js/).

However Simplifier insists that the Constraint has been violated. When using the FHIRPath tester, the subsetOf does not work for string and uri values, even-tough uri values are of the type string. 

Below are the example,package and profile json:
[Fhirpath.zip](https://github.com/FirelyTeam/fhir-net-api/files/4722352/Fhirpath.zip)

**Comment by simoneOnFhir** [comment]
The issue seems to be that Bundle.entry.fullUrl returns a collection of URIs where it should return a collection of strings, see http://hl7.org/fhir/fhirpath.html#types

**Comment by marcovisserFurore** [comment]
In the following unittest I can prove that this is indeed a bug

```c#
        public void Test1389()
        {
            var resource = new Composition();
            resource.Author.Add(new ResourceReference("http://example.com"));

            var bundle = new Bundle();
            bundle.Entry.Add(new Bundle.EntryComponent
            {
                Resource = resource,
                FullUrlElement = new FhirUri("http://example.com")
            });

            // subsections of the whole expression are evaluated correctly
            var fullUrl = bundle.Select("Bundle.entry.fullUrl").FirstOrDefault() as FhirUri;
            var reference = bundle.Select("Bundle.entry.descendants().reference").FirstOrDefault() as FhirString;
            Assert.AreEqual("http://example.com", fullUrl.Value);
            Assert.AreEqual("http://example.com", reference.Value);

            // even in combination they are equal
            Assert.IsTrue(bundle.Predicate("Bundle.entry.descendants().reference = Bundle.entry.fullUrl"));

            // but in combination with 'subsetOf' it does not work: 
            // the argument of the subsetOf function (Bundle.entry.fullUrl) is empty...
            Assert.IsTrue(bundle.Predicate("Bundle.entry.descendants().reference.subsetOf(Bundle.entry.fullUrl)"));
        }
````

The argument of `subsetOf` is empty

**Comment by marcovisserFurore** [comment]
The expression is not correct. At the moment when `subsetOf` is executed, the focus is on `Bundle.entry.descendants().reference`. It does not know the start context anymore, so the argument of `subsetOf` will be empty.

So the following statement will work:
```
Bundle.entry.descendants().reference.subsetOf(%context.entry.fullUrl)"
```
The environment variable `%context` will hold the original node that was passed to the evaluation engine before starting the evaluation.

**Comment by simoneOnFhir** [comment]
Thank you!

Tested it and it works!

Mit freundlichen Grüßen
Simone Heckmann

Geschäftsführerin / CEO
Gefyra GmbH
+49 (0) 177 - 39 39 36 7
sh@gefyra.de


<http://www.gefyra.de>





Am Do., 25. Juni 2020 um 14:53 Uhr schrieb Marco Visser <
notifications@github.com>:
