### ISSUE TITLE
Questionnaire doesn't implement IVersionableConformanceResource 

### ISSUE THREAD

**Issue by Bulgrak** [FirelyTeam/fhir-net-api#1391]
I noticed that Questionnaire doesn't implement IVersionableConformanceResource even though it has the properties that are specified in the interface. 

I have written about the issue here as well: 
https://chat.fhir.org/#narrow/stream/179171-dotnet/topic/Questionnaire.20and.20IVersionableConformanceResource

**Comment by ewoutkramer** [comment]
Nice addition - if you can, would you mind making a PR for us @Bulgrak ?

**Comment by Bulgrak** [comment]
Sure, which branch should I branch out from? I'm thinking develop-r4, but just want to make sure that I'm doing it correctly.
