### ISSUE TITLE
FHIRPath compiler throws exception for escaped whitespace check

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/fhir-net-api#1396]
Trying to execute any FHIRPath statement containing `matches('\\S')` leads to an exception in the FHIRPath compiler:

'Compilation failed: Parsing failure: unexpected '('; expected end of input (Line 1, Column 13); recently consumed: st.matches'

**Comment by alexzautke** [comment]
Issue is shown in a unit test in branch "bugfix/1396-fhirpath-matches"

**Comment by alexzautke** [comment]
Should be the same for any other escaped regex, like `\\d+`

**Comment by marcovisserFurore** [comment]
@alexzautke , you use the matches function as follows: 

```
        [TestMethod]
        public void TestSelectNonWhiteSpaceCharacters()
        {
            var patient = SourceNode.Resource("Patient", "Patient", SourceNode.Valued("id", "test"));
            var typedElement = patient.ToTypedElement();

            var success = typedElement.IsBoolean("test.matches('\\S')", true);
            Assert.IsTrue(success);
        }
```

I changed the FhirPath expression to `"Patient.id.where(matches('\\S')).exists()` and then I don't get any compilation errors and the expression evaluates as expected. 

@ewoutkramer : how should the function `matches(regex: String)` be used? I have the feeling the expression `test.matches('\\S')` is not a correct usage.

**Comment by ewoutkramer** [comment]
Mmmmm....if `a.matches().b` compiles, but `a.matches()` does not, this starts to look like a parsing grammar error.

**Comment by alexzautke** [comment]
@marcovisserFurore Thanks for the workaround, I will see if I can integrate that into my solution.
I can see however that the FHIR specification itself uses <collection>.matches('<regex>') in some of the official constraints. See for example sdf-0: http://hl7.org/fhir/structuredefinition.html

**Comment by marcovisserFurore** [comment]
I think I found the problem. The compiler is confused about the number of backspaces. If I do the following: 
```
var success = typedElement.IsBoolean("id.matches('\\\\S')", true);
```
Then it works. Which is actually the same as:
```
var success = typedElement.IsBoolean(@"id.matches('\\S')", true);
```

So the escaping is the here the problem.

**Comment by marcovisserFurore** [comment]
It raises now the question why the first workaround is working:

```Patient.id.where(matches('\\S')).exists()```
 
This should actually fail, because `\S` is not a valid escape character.

**Comment by marcovisserFurore** [comment]
I've tested the above expression again (`Patient.id.where(matches('\\S')).exists()`) on branch `1.x/develop`, and I got also Parser error, which should be expected.

So it should be 4 backslashes, or preceded by `@`, so:
```
  @"Patient.id.where(matches('\\S')).exists()"
```
or
```
Patient.id.where(matches('\\\\S')).exists()
```

**Comment by marcovisserFurore** [comment]
I close this issue, because it is no bug.
