### ISSUE TITLE
 Fhir Rest API 

### ISSUE THREAD

**Issue by zahialajori** [FirelyTeam/fhir-net-api#1398]
What is the possibility  to rewrite the Fhir Rest API to use the HttpClient ? 
and why it is not supported yet?

Thanks,

**Comment by marcovisserFurore** [comment]
Hi @zahialajori . In the next major version we have refactored `FhirClient` and we are using `HttpClient` instead of the `HttpWebRequest `. In fact, we are done developing this, but we are waiting for more features, so we hope to release this new FhirClient (fhir-net-api v2.0) in this summer.

**Comment by zahialajori** [comment]
thanks @marcovisserFurore  for your feedback , is there possibility to merge this to R4 branch . 
and please what is the expected date to have HttpClient released.

Thanks in advance,

**Comment by marcovisserFurore** [comment]
Since yesterday we also merged this into the develop-r4 branch. 
Version 2.0 will be a major release and we will bring it out as a beta release first. I hope that would be in a few months.

**Comment by marcovisserFurore** [comment]
I am closing this issue, because it has been answered. Keep an eye on our release page (https://github.com/FirelyTeam/fhir-net-api/releases) for upcoming releases.
