### ISSUE TITLE
R4 Goal resource Start element serialization issue

### ISSUE THREAD

**Issue by justintubbs** [FirelyTeam/fhir-net-api#1404]
R4 Goal resource specifies the following:
![image](https://user-images.githubusercontent.com/12716768/86047125-a098da80-ba0b-11ea-9fde-8d90d9ec55f3.png)

In the Firely R4 https://www.nuget.org/packages/Hl7.Fhir.R4/ (v1.7.0) the Goal FHIR resource has a Start property with `Element` type which should support a C# FhirDateTime type (at least at compile time it does):
![image](https://user-images.githubusercontent.com/12716768/86047182-be663f80-ba0b-11ea-84bf-b39ea05649c4.png)

I'm able to serialize from C# FHIR Model object to XML string:
```
    <Goal>
      <id value="2" />
      <startDateTime value="2017-07-14T20:25:51+00:00" />
      <statusDate value="2017-06-07T14:05:19Z" />
    </Goal>
```

When deserializing from XML > C# FHIR Model object I get the following runtime error:
```Message: System.FormatException : Type checking the data: Choice element 'startDateTime' is suffixed with unexpected type 'DateTime' (at Bundle.entry[0].resource[0].contained[0].startDateTime[0])```

![image](https://user-images.githubusercontent.com/12716768/86048128-35e89e80-ba0d-11ea-812f-d6ab56f2c6f6.png)

Unit Test Code:
```
        [Fact]
        public void GoalResource_Valid()
        {
            // Arrange
            var goal = new Hl7.Fhir.Model.Goal()
            {
                Id = "1",
                Start = new Hl7.Fhir.Model.FhirDateTime(DateTime.Now)
            };
            var serializer = new FhirXmlSerializer();
            var parser = new FhirXmlParser();

            // Act
            string serializedXml = serializer.SerializeToString(goal);

            // Assert
            Assert.False(string.IsNullOrWhiteSpace(serializedXml), $"Expected {nameof(serializedXml)} to be not NULL or whitespace");
            var model = parser.Parse<Hl7.Fhir.Model.Goal>(serializedXml);
            Assert.NotNull(model);
        }
```

Seems like the FhirXmlParser does not support the XML markup that can be generated using the same library, I believe this might be a defect/bug that needs to be resolved.

**Comment by justintubbs** [comment]
The StatusDate property has this same issue as well:
![image](https://user-images.githubusercontent.com/12716768/86049884-2c146a80-ba10-11ea-9579-5a2d1aae13bf.png)

```Message: System.FormatException : Type checking the data: Choice element 'scheduledDateTime' is suffixed with unexpected type 'DateTime' (at CarePlan.activity[0].detail[0].scheduledDateTime[0])```

**Comment by brianpos** [comment]
The type is a `Hl7.Fhir.Model.Date`, not a `Hl7.Fhir.Model.FhirDateTime` which is why you're having the issue.

**Comment by ewoutkramer** [comment]
Brian is right - although the C# class allows any element (by having a property of type `Element`), it does not mean that you can actually use all subclasses: the specification is right, only Date is allowed here. 

The serializer does not check it on the way out, but the parser does on the way in.  It's debatable whether that is consistent, and we will probably revisit this in a future major release (since changing that would be a breaking change).

It would have been helpful here if C# knew the concept of union types (like C before it, or F#), so we could have declared the exact allowed datatypes structurally here, but alas.

**Comment by brianpos** [comment]
We could put some runtime type checking in there in the setter...
(And @justintubbs , I really want to commend you on one of the most detailed issue reports, you've definitely done your groundwork here - thanks, it made it easier to spot the issue)

**Comment by justintubbs** [comment]
Thanks for the feedback @brianpos I was able to get this working by using `Hl7.Fhir.Model.Date` instead of `Hl7.Fhir.Model.FhirDateTime`

Working Unit Test code here:
```
        [Fact]
        public void GoalResource_Valid()
        {
            // Arrange
            var goal = new Hl7.Fhir.Model.Goal()
            {
                Id = "1",
                Start = new Hl7.Fhir.Model.Date(DateTime.Now)
            };
            var serializer = new FhirXmlSerializer();
            var parser = new FhirXmlParser();

            // Act
            string serializedXml = serializer.SerializeToString(goal);

            // Assert
            Assert.False(string.IsNullOrWhiteSpace(serializedXml), $"Expected {nameof(serializedXml)} to be not NULL or whitespace");
            var model = parser.Parse<Hl7.Fhir.Model.Goal>(serializedXml);
            Assert.NotNull(model);
        }
```
