### ISSUE TITLE
Continue after SearchUsingPost throws exception

### ISSUE THREAD

**Issue by holpit** [FirelyTeam/fhir-net-api#1405]
The Continue method executed after a SearchUsingPost, throw an exception. 
The same operation with SearchAsync works fine and also using Postman with POST, the operation is successfully.

The problem is that Continue does always a GET request
First request: SearchUsingPost
**POST** /ClinicalImpression/_search HTTP/1.1
_count | 2
_include | ClinicalImpression:subject

Call Continue on bundle of previous request:
**GET** /ClinicalImpression/_search?ct=NTA5ODI1Mzg0ODc2NTY4MDAwMQ%3D%3D HTTP/1.1

Operation was unsuccessful because of a client error (BadRequest). OperationOutcome: Overall result: FAILURE (1 errors and 0 warnings)

[ERROR] (no details)(further diagnostics: Id must be any combination of upper or lower case ASCII letters ('A'..'Z', and 'a'..'z'), numerals ('0'..'9'), '-' and '.', with a length limit of 64 characters. (This might be an integer, an un-prefixed OID, UUID, or any other identifier pattern that meets these constraints.)) (at ResourceKey.Id).

Where I'm wrong?
Thank you

**Comment by ewoutkramer** [comment]
Yes, `Continue()` will always do a `GET`, as described in the FHIR specification: http://hl7.org/fhir/http.html#paging

"In the case of a search, the initial request may be made via a POST, **but the follow up page requests will be made via GET** requests. However servers SHOULD allow for a client to convert the follow up requests to be made via a POST."

this is what the client does - but clearly the server is not expecting that.  The server should create a "next" link on the first result from the POST that contains enough state information for the client to be able to continue with a `GET`.

**Comment by ewoutkramer** [comment]
Which server are you using?  @cknaap - how does Vonk solve this?

**Comment by holpit** [comment]
Thank you @ewoutkramer , I got it.
I'm using Microsoft Fhir Server https://github.com/microsoft/fhir-server on sqlServer.
I'll redirect this issue to the Microsoft's repository
