### ISSUE TITLE
Leading space not correctly serialized / parsed (Json)

### ISSUE THREAD

**Issue by pieteckhart** [FirelyTeam/fhir-net-api#1407]
Hi,

I'm trying to set a extension value to some string containing a leading space character.

Why?

> If only a house letter suffix is known, communicate that with a leading space.
https://simplifier.net/NictizSTU3-Zib2017/nl-core-address.

It seems that in both serialization and parsing the space character is trimmed off.

I don't know if this is only a problem with extensions but I do have a failing unit test demonstrating what I was expecting.

I would love to make a PR for this, is it Ok if I only provide the failing test without a fix?
Otherwise here it is:

```C#
        [TestMethod]
        public void ParseExtensionWithLeadingSpace()
        {
            var organization = new Organization
            {
                Address = new List<Address>()
                {
                    new Address()
                    {
                        LineElement = new List<FhirString>
                        {
                            new FhirString("foo")
                            {
                                Extension = new List<Extension>
                                {
                                    new Extension
                                    {
                                        Url = "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-buildingNumbersuffix",
                                        Value = new FhirString(" <-Leading space")
                                    }
                                }
                            }
                        }
                    }
                }
            };

            //Should still have leading space before serialization
            Assert.AreEqual(" <-Leading space", organization.Address.First().LineElement.Single().Extension.Single().Value.ToString());

            var serializer = new FhirJsonSerializer();
            var json = serializer.SerializeToString(organization);

            //Json should still have the leading space
            Assert.IsTrue(json.Contains("\" <-Leading space\""));

            var poco = new FhirJsonParser().Parse(json) as Organization;

            //After parsing should still have leading space
            Assert.AreEqual(" <-Leading space", poco.Address.First().LineElement.Single().Extension.Single().Value.ToString());
        }
```

**Comment by mmsmits** [comment]
Hi @pieteckhart, 
This behaviour is intentional, and conform the FHIR spec. In XML, whitespaces in value attributes SHOULD be trimmed, to conform to the XML schemas. (https://www.hl7.org/fhir/xml.html).
To not cause confusion, we choose to trim these in the JSON serializer as well. 
(https://www.hl7.org/fhir/json.html#xml)

I think this is an issue that should be handled by Nictiz, since they apparently add meaning to whitespaces at the end of some strings. When implementers will use those in XML, the whitespace will be trimmed, and therefor cause loss of information. 
https://www.hl7.org/fhir/xml.html
