### ISSUE TITLE
Finding all references in any resource in a bundle

### ISSUE THREAD

**Issue by jerchap** [FirelyTeam/fhir-net-api#1414]
Is there away to somehow traverse all resources in a bundle and find all references to other resources? Even using reflection?

**Comment by alexzautke** [comment]
You can do this via a FHIRPath select. Have a look here: https://github.com/FirelyTeam/Vonk.Plugin.DocumentOperation/blob/develop/Vonk.Plugin.DocumentOperation/DocumentService.cs (line 166). You can re-use the same FHIRPath statement even if you use a Bundle POCO instead of an ITypedElement.

**Comment by ewoutkramer** [comment]
And, as I wrote on Zulip, you can use the POCO's NamedChildren() function to list all elements, without using reflection. In fact, this is used by the FhirPath engine to get to POCO data without having to resort to (slow) reflection code.

**Comment by ewoutkramer** [comment]
I consider this question answered, closing the issue.
