### ISSUE TITLE
Add expansion parameters to ValueSet $expand

### ISSUE THREAD

**Issue by MatthijsvdWielen** [FirelyTeam/fhir-net-api#1418]
There is currently limited support for $expand on Vonk: http://docs.simplifier.net/vonk/features/terminology.html#valueset-expand
Because expansion parameters are not supported in the api at the moment, these can not be implemented on Vonk. 

Feature request: Would it be possible to add funtionality to the api so that includeDesignations are shown in expansion? 

Expansion parameters: https://www.hl7.org/fhir/valueset.html#parameters

**Comment by marcovisserFurore** [comment]
Work: 
- 8 hours + review and unittests
- release in 1.9
