### ISSUE TITLE
Function `IsCoreModelType`  should accept null as well

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/fhir-net-api#1451]
The function `ModelInfo,IsCoreModelType(string name)` cannot handle null as an argument, but throws an exception. Perhaps we can adjust the function like this?

```
 public static bool IsCoreModelType(string name) => name == null ? false : FhirTypeToCsType.ContainsKey(name);
```

instead of 
```
 public static bool IsCoreModelType(string name) => FhirTypeToCsType.ContainsKey(name);
```

**Comment by ewoutkramer** [comment]
I think it should throw ArgumentNull...didn't it do that?    A type "null" does not make sense, so I am of the opinion we should not accept that as an argument - it's most likely an error on the caller's side, he/she might not even be aware this gets called with "no type" as the argument.

**Comment by ewoutkramer** [comment]
Hearing no further about this, I am closing this issue until reporter reopens.
