### ISSUE TITLE
DateTimes in the JSON response being manipulated by Newtonsoft

### ISSUE THREAD

**Issue by zachdev** [FirelyTeam/fhir-net-api#1456]
DateTimes appear to be undergoing manipulation by the underlying Newtonsoft library FhirClient uses.

The times and time zones are being parsed and converted to the locale of the machine where the code is running.

Source DateTime:

"effectiveTime" : "2020-07-29T08:30:24 -04:00"

After parsing by FhirClient:

"effectiveTime" : "2020-07-29T07:30:24 -05:00"

This behavior is avoided in Newtonsoft by setting the JsonReader's DateParseHandling property to DateParseHandling.None, but FhirClient abstracts this away and does not allow an obvious way to enable this setting.

Is this an actual issue, or perhaps some FhirClient parse setting that was missed?

**Comment by ewoutkramer** [comment]
Hi @zachdev, it must be more subtle than this, since the newtonsoft Json parser is initialized exactly like you said in this private function in the parser:

```
   private static JsonReader JsonReaderFromTextReader(TextReader input)
        {
            return new JsonTextReader(input)
            {
                DateParseHandling = DateParseHandling.None,
                FloatParseHandling = FloatParseHandling.Decimal,
                CloseInput = false      // Unbelievable, the default is 'true' (and is false for the XmlReaderSettings :-()
            };
        }
```

Also, the parser is extensively tested using round-trip tests with data containing timezones.

That being said, the FhirClient has been rewritten in 2.0-beta, are you using that version?  Maybe we do have a glitch somewhere.

**Comment by ewoutkramer** [comment]
Trying to pinpoint the problem: Is the "source datetime" coming over the wire as you've shown here?  And the "after parsing" text above, is that as shown after serialization?

**Comment by zachdev** [comment]
Hi Ewout, and thank you for the fast reply.

Yes, the "source datetime" is the value in our data source. After executing a Search using the FhirClient, we appear to be seeing that value being mutated to the timezone where the client is running. Our consumers are accepting the data as-is, with no timezone conversions happening on their end, so this is causing some confusion.

Unfortunately, I am off-work this week and cannot investigate further until next week, however I do see that DateParseHandling.None is indeed being applied here.  Something "more subtle than this", or perhaps even unrelated, may be causing this issue.

**Comment by zachdev** [comment]
I am able to confirm that this is **not an issue with the FhirClient**.  It was discovered that there was some additional serialization using Newtonsoft occurring in our code that was causing the problem. I am not sure how I overlooked this originally.

I am very sorry for any time wasted on investigating this.

Closing.
