### ISSUE TITLE
Error in FHIR JSON for AllergyIntolerance

### ISSUE THREAD

**Issue by yaminipopcornapps** [FirelyTeam/fhir-net-api#1466]
Hi,
I am trying to parse the below JSON for AllergyIntolerance (from epic) when I am receiving the below error for Choice field Onset. In the specification I don't see the field to be having two options unlike the deceased field in Patient JSON. Below snapshots for reference

AllergyIntollerance:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/60649604/90506312-a5f3e500-e171-11ea-9875-6961bfbde46a.png)

Patient
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/60649604/90506369-c623a400-e171-11ea-977a-e44259dd79b5.png)

**Comment by marcovisserFurore** [comment]
In the FHIR spec (https://www.hl7.org/fhir/allergyintolerance.html) you can see that the attribute `onset` is a choice field (a choice of 5 datatypes). 

![image](https://user-images.githubusercontent.com/31658535/90507985-1e00e180-e157-11ea-82dd-265efc620f1c.png)

**Comment by marcovisserFurore** [comment]
BTW, there are 2 `onset` fields. One field I mentioned in my previous post which is a choice field, and the other `onset` field is a part of `reaction`, which is *not* a choice field, but is of type datetime. Maybe you mixed them up?

**Comment by yaminipopcornapps** [comment]
When I try to parse that JSON am not getting it suffixed.

![image](https://user-images.githubusercontent.com/60649604/90508436-60d1b200-e175-11ea-9fe2-8d18702ad088.png)

**Comment by yaminipopcornapps** [comment]
This how I am getting the response

![image](https://user-images.githubusercontent.com/60649604/90509995-d63e8200-e177-11ea-92ea-6813c35d6a3a.png)

**Comment by marcovisserFurore** [comment]
Where is this search bundle coming from? 

When I perform a search action on the Vonk FHIR server, I will get the following response:

```
{
  "resourceType": "Bundle",
  "type": "searchset",
  "entry": [
    {
      "fullUrl": "https://vonk.fire.ly/AllergyIntolerance/e51ff594-1558-4938-ba13-155c819c3c31",
      "search": {
        "mode": "match"
      },
      "resource": {
        "resourceType": "AllergyIntolerance",
        "identifier": [
          {
            "value": "P10105VNADT108610302"
          }
        ],
        "clinicalStatus": "active",
        "verificationStatus": "confirmed",
        "category": [
          "medication"
        ],
        "code": {
          "coding": [
            {
              "system": "http://snomed.info/sct",
              "code": "08610302",
              "display": "DAIRY",
              "userSelected": true
            }
          ]
        },
        "patient": {
          "reference": "https://vonk.fire.ly/Patient/825eaaba-0b56-49ce-9729-80092706b968"
        },
        "onsetDateTime": "2019-10-17",
        "reaction": [
          {
            "substance": {
              "coding": [
                {
                  "system": "http://snomed.info/sct",
                  "code": "08610302",
                  "display": "DAIRY",
                  "userSelected": true
                }
              ]
            },
            "manifestation": [
              {
                "coding": [
                  {
                    "system": "http://snomed.info/sct",
                    "code": "ITCHING",
                    "userSelected": true
                  }
                ]
              }
            ],
            "onset": "2019-10-17"
          }
        ],
        "id": "e51ff594-1558-4938-ba13-155c819c3c31",
        "meta": {
          "versionId": "133a4cde-c527-4100-95b2-0f339165f2a0",
          "lastUpdated": "2020-08-18T11:18:25.375+00:00"
        }
      }
    },
```

which is correct: 
```
 "onsetDateTime": "2019-10-17",
```

So I think the server produces a incorrect Json. Which server you are using?

**Comment by yaminipopcornapps** [comment]
Thank you for the reply. The response that I am trying to parse is from EPIC sandbox.

**Comment by marcovisserFurore** [comment]
And I think you used DSTU2 version. In that version the field `onset` was not a choice field yet. If you try to parse it with a STU3 or R4 parser, then you will get errors indeed.
