### ISSUE TITLE
How to get rid of pagination when fetching resource in r4 api?

### ISSUE THREAD

**Issue by aviskarkc10** [FirelyTeam/fhir-net-api#1472]
Currently the api returns 10 data by default. What should I pass in order to get rid of pagination?

I did find this specification: https://tools.ietf.org/html/rfc5005

But couldn't really get it to work.

Also forgive me if this isn't the right place to ask this.

**Comment by marcovisserFurore** [comment]
You can influence the number of returned resources by setting a limit in the client. But be aware that the server can decide to return less resources (see http://hl7.org/fhir/search.html#count).

In the fhir-net-api you can set the limit like this:

```
            using var client = new FhirClient(_endpoint);
            var srch = new SearchParams()
                .Where("name=Bill")
                .LimitTo(10);
            var result = await client.Search<Patient>(srch);
```

**Comment by aviskarkc10** [comment]
Isn't there a way to override this and make the api return all data without pagination?

**Comment by marcovisserFurore** [comment]
The api does not return data, the FHIR server does. And it is, by specification, the server that decides the maximum of resources. In the client you can influence this a bit by changing the limit (`_count` parameter). In order to keep the load on clients, servers and the network minimized, the server may choose to return the results in a series of pages.

**Comment by aviskarkc10** [comment]
https://github.com/microsoft/fhir-server

This one

**Comment by marcovisserFurore** [comment]
As far as I know the default is set to 500. This number is configured in `appSettings.json`
```
"Bundle": {
    "EntryLimit": 500
 }
```
But for more information about the Microsoft fhir-server, you can contact Microsoft.

**Comment by aviskarkc10** [comment]
Thanks a lot for your help :+1:
