### ISSUE TITLE
Navigate in FHIRPath CollectionOperators does not allow selecting children beginning with upper case names

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/fhir-net-api#1484]
When working with logical models it is not uncommon to have elements starting with upper case characters.
The Navigate method in CollectionOperators.cs does currently have a short-cut for elements beginning with upper case characters. It only works under the assumption that all elements of this kind are a resource type. The API should also allow to select any matching children in case the instance type of the element is not a resource type.

**Comment by joelemaltais** [comment]
Depending on effort and time needed for this change I'll have to decide whether to modify all logical models as a workaround.

**Comment by alexzautke** [comment]
Created a unit test in ElementNodeTests (see bugfix/1484-select-logical-model-upper-case). Is there an edge case that I am missing?

**Comment by marcovisserFurore** [comment]
@alexzautke , I checked out your branch and point common to the latest release (2.0.0-beta2) and the unit test `TestFpNavigate` is still succeeding. So does that mean that is already been solved, or do we need more tests?

**Comment by alexzautke** [comment]
@marcovisserFurore The issue should have been solved by my changes. @ewoutkramer mentioned before that there were some edge cases where the new behaviour wouldn't work. Therefore I created the test so you could check if I missed anything.

**Comment by alexzautke** [comment]
Please double check the test to see if there are other combination that need to work. Otherwise I can create a PR.

**Comment by alexzautke** [comment]
Fixed by #1526
