### ISSUE TITLE
[Question] How to match bundle search results with original conditions

### ISSUE THREAD

**Issue by MyEidos** [FirelyTeam/fhir-net-api#1514]
I am doing a search with multiple conditions like: 

```
var searchBuilder = new TransactionBuilder(endpoint, BundleType.Batch);

SearchParams condition1 = new SearchParams();
condition1.Add("identifier", "first");

SearchParams condition2 = new SearchParams();
condition2.Add("identifier", "second");

 searchBuilder.Search(condition1 , "Patient");
 searchBuilder.Search(condition2, "Patient");
```

So how can I match condition1 and condition2 with search results resources? 
Obviously, the example above is simple and I can just recheck IDs again in the response bundle, but it is not an option. 

Any advice?
Thanks.

**Comment by mmsmits** [comment]
Hi, I'm trying to understand what you would like to do exactly. Can you elaborate a little bit?
Are using the API as a client or as a server?

Do you want to combine the search parameters into a single result? 

For example:

```
Give me all patients with condition 1 AND condition 2?

or

Give me all patients with condition 1 OR condition 2?
```

Or do you want something entirely different?

**Comment by MyEidos** [comment]
Hi @mmsmits 

I am using API as a client. 

Let me try to explain with an example:

Assume 2 users requested some data, first wants to receive a patient with the family "Doe", second with the family "Smith".
I want to get that data in 1 request, so I am creating a bundle, something like 

```
SearchParams condition1 = new SearchParams();
condition1.Add("family", "Doe");

SearchParams condition2 = new SearchParams();
condition2.Add("family", "Smith");

 searchBuilder.Search(condition1 , "Patient");
 searchBuilder.Search(condition2, "Patient");
```

Posted it and received a response: bundle with 2 included bundles as search results. Everything is good so far. 

Now I want to send Patient "Doe" to the first user and patient "Smith" to the second user. But I am not sure which sub bundle is for which user. 


Now I save condition as string  $"/{resource.TypeName}?{condition.ToUriParamList().ToQueryString()}" and compare with SearchQuery in response. 

Probably it is not related to fhir-net-api itself but to FHIR specification, so please feel free to close this issue if you don't see a better solution. 
Thanks.

**Comment by ewoutkramer** [comment]
Hi @MyEidos - indeed the searches are defined on the FHIR server spec only, so we have no client-side equivalent in the API.
