### ISSUE TITLE
notation of search parameters

### ISSUE THREAD

**Issue by felixwimmer** [FirelyTeam/fhir-net-api#1528]
We discovered a difference between the VONK FHIR Server and the Microsoft FHIR Server regarding the notation of search parameters (with or without '\_').

For example we want to select all "Conditions" for a specific patient ("subject").
For the VONK FHIR Server the search parameter has to be „subject:Patient“ (without '\_') and for the Microsoft FHIR Server it has to be „\_subject:Patient“ (with '\_').
 
Can you explain this difference? For us it is important because we want evaluate the interchangeability of these two products.

**Comment by mbaltus** [comment]
The FHIR specification lists search parameters for each resource type at the bottom of the resource page. Each resource type that can point to a subject of type Patient, will have the 'patient' parameter defined, as well as the 'subject' parameter. For the latter you will have to specify the type, as you did in your example. The '_' prefix is used in the FHIR specification for parameters that are available for all resource types.
Vonk implements the standard search parameters defined in the specification. I do not know why the Microsoft server implements a '_subject' parameter, but it is not a standard one.
