### ISSUE TITLE
Searching for Condition throws exception

### ISSUE THREAD

**Issue by bbieniek** [FirelyTeam/fhir-net-api#1538]
**Describe the bug**
While running a search for condition on R4 nuget package, the following code throws exception:
```
var client = new FhirClient(@"https://vonk.fire.ly");
var conditions = client.Search<Condition>();
```

Type checking the data: Since type CodeableConcept is not a primitive, it cannot have a value (at Bundle.entry[0].resource[0].clinicalStatus[0]

**To Reproduce**
1. Install R4 FHIR nuget.
2. Try to run search:
```
var client = new FhirClient(@"https://vonk.fire.ly");
var conditions = client.Search<Condition>();
```

**Expected behavior**
Should return valid conditions list

**Version used:**
 - FHIR Version: R4
 - Version: 1.9.0

**Comment by marcovisserFurore** [comment]
Hi @bbieniek ,

Thanks for contacting us.

I had a look at your issue. You are trying to search for R4 Conditions on a STU3 server (Vonk defaults to STU3). When you will do the following it will work:

```c#
var client = new FhirClient(@"https://vonk.fire.ly/r4");
var conditions = client.Search<Condition>();
```

**Comment by bbieniek** [comment]
Thanks a lot. That helped 👍
