### ISSUE TITLE
Hide private backing variables in POCO's for debugger

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/fhir-net-api#218]
There is an attribute we could add to the POCO's to avoid showing both as visible below:

![hideprops](https://cloud.githubusercontent.com/assets/2276305/15963712/5e9b097c-2f14-11e6-9c64-e60615dbd834.jpg)

http://stackoverflow.com/questions/754393/hiding-fields-from-the-debugger

**Comment by tstolker** [comment]
Ewout, I think that would be great!

**Comment by brianpos** [comment]
Now that I'm looking at doing this, I'm not so sure.
The _native fields have no side effects, whereas the _native properties do have side effects, lazy creators.
This would remove the ability to know if the object was created (and will hide some types of bugs)

**Comment by brianpos** [comment]
Can we close this issue now please?
