### ISSUE TITLE
Add a call-back on DirectorySource (and possibly others) when duplicate canonicals are found

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/fhir-net-api#393]
This is so the caller can determine what to do with duplicates.  Default behaviour will be:

* Determine whether the filenames are the same (i.e. an xml and json version of the same thing) -> chose the xml version
* Same url in different files -> throw exception

The MultiSource may also benefit from this functionality

**Comment by ewoutkramer** [comment]
I think some of this should be visible in an ArtifactSummary instead of throwing?

**Comment by wmrutten** [comment]
Definitely!
The ArtifactSummaryGenerator does not care about duplicate canonical urls.

Currently, method `DirectorySource.ListSummaries()` also initializes creates a lookup Dictionary to map CanonicalUrls to FileNames. If the content directory contains duplicate canonical urls, then the initialization will fail and throw a `CanonicalUrlConflictException` and the summary list remains empty.

Proposal: do not throw when fetching summaries; allow duplicate canonical urls in list of summaries.
Instead, move error handling to method `ResolveByCanonicalUrl`. By default, if the content directory contains multiple resources that match the specified url, then throw a `CanonicalUrlConflictException`.

Once `DirectorySource` (and other `IResourceResolver` implementations) implement the new error event interface introduced by the validator, then we can allow clients to override the default behavior by hooking the event.
