### ISSUE TITLE
[Validation] Validation fails if Element[0] of the differential is sliced

### ISSUE THREAD

**Issue by patrick-werner** [FirelyTeam/fhir-net-api#424]
When POSTing a StructureDefinition to the public VONK server with a sliced StructureDefinition.differential[0] POSTing fails with:

> Instance failed constraint sdf-20 &quot;No slicing on the root element&quot;

Differential Part of the StructureDefinition:

`<differential>
    <element id="Patient.identifier">
      <path value="Patient.identifier" />
      <slicing>
        <discriminator>
          <type value="value" />
          <path value="system" />
        </discriminator>
        <rules value="open" />
      </slicing>
    </element>
  </differential>`

[StructureDef to reproduce](https://pastebin.com/tXTMn1yw)
[Full Response](https://pastebin.com/3ZTe1MfC)

**Comment by patrick-werner** [comment]
it seems the problem is contained in the FHIR Spec itseld in: sfd-20
https://chat.fhir.org/#narrow/stream/conformance/subject/sdf-20.20in.20StructureDefinition.20seems.20incorrect

**Comment by patrick-werner** [comment]
Bug was already known and tracked here: https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=13768&start=0

**Comment by patrick-werner** [comment]
Bug was already known and tracked here: https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=13768&start=0

**Comment by ArdonToonstra** [comment]
Would it be possible to change the validator so that it skips this bug of the spec? Instead of waiting for the R4 release?

**Comment by ArdonToonstra** [comment]
I am aware of that, as I have done it a couple of times as well. However, a lot of users on Simplifier will not know that you could place a dummy constraint above the slice or extension if this is the first element.

**Comment by ewoutkramer** [comment]
@brianpos, should we tweak the R3 spec, like we did with many invariants of the DSTU2 spec to fix it instead of disabling it?

**Comment by brianpos** [comment]
If it's clear that it was broken, and we're just fixing based on r4 definition, i have no objections.

**Comment by jkiddo** [comment]
Forge seems to also generate this snippet ... and the IG publisher is not fond of it

**Comment by ewoutkramer** [comment]
What do we do about it?  Bend our head and always provide a root?

**Comment by patrick-werner** [comment]
shouldn't be sdf-20 part of the upcoming DSTU3 technical correction release?
I think pre-applying the needed fix to the .net api would be better than always providing a unnecessary root.

**Comment by ArdonToonstra** [comment]
I would vote for pre-applying the needed fix. 
Link to relevant chat on zulip: https://chat.fhir.org/#narrow/stream/179240-Announcements/topic/Technical.20corrections.20for.20FHIR.20R3

**Comment by wmrutten** [comment]
I'd strongly prefer all our FHIR products to be lenient on input and strict on output.

These limitations of the IG Publisher are know and reported for a long time (> 1y I think) and should really be fixed by their maintainers.

**Comment by ewoutkramer** [comment]
Discovered this item has escaped my attention since I did not triage it.  Anyone know what the status is?

**Comment by wmrutten** [comment]
https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Invalid.20invariant.20sdf-20.20in.20STU3
https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=13768
https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=20339

**Comment by wmrutten** [comment]
Note: faulty invariant sdf-20 has been corrected in R4:
http://hl7.org/fhir/structuredefinition.html#invs
`element.where(path.contains('.').not()).slicing.empty()`
The new expression now matches the actual root element (no "." in path), instead of the first element in the list.

**Comment by ewoutkramer** [comment]
The technical correction that is bound to be published this month will contain fixes for both tracker items, so it seems this story is coming to an end soonish.

**Comment by ArdonToonstra** [comment]
@ewoutkramer, @marcovisserFurore , isn't this fixed with the technical correction in oct 2019? Can this issue be closed?

**Comment by ewoutkramer** [comment]
Yes, I have checked this has been corrected in 3.0.1 as well. Closing this issue (finally).
