### ISSUE TITLE
DocumentReference bundle taking a lot of memory space

### ISSUE THREAD

**Issue by Vineet15** [FirelyTeam/fhir-net-api#579]
Hello,

We are using STU3 0.94.0. While trying to read a document reference with content in binary we have noticed that for a document of size 100 MB ends up creating a bundle and causes the memory to spike to over a GB.

We have not applied any Validator of our own. I am assuming that the client does not apply one on its own. There did not seem to be an option like "DEFAULT_SERVER_VALIDATION_MODE" which is present in the Java client.

This only seems to be happening for the DocumentReference resource on requesting Attachment.

Could there be another reason which could be causing this spike in memory usage?

Thanks

**Comment by ewoutkramer** [comment]
This sounds similar to #603.

**Comment by brianpos** [comment]
Can you put the resource somewhere we can take a look at to try and work out what is going on?
If this is a single resource with a leave binary, not sure this is the same issue.
