### ISSUE TITLE
[Validation] Use R4 fix for sdf-9 constraint in the STU3 validator

### ISSUE THREAD

**Issue by ArdonToonstra** [FirelyTeam/fhir-net-api#610]
The expression of sdf-9 in STU3 contains a 'bug'. [Gforge tracker item 13721](https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=13721&start=0) provides a fix which has been approved.

Can we use the R4 expression for the STU3 validator? 

A bit related to: https://github.com/ewoutkramer/fhir-net-api/issues/424

**Comment by wmrutten** [comment]
Agreed, I consider this a technical correction.
Related: #618

**Comment by ewoutkramer** [comment]
Should be fixed in the recent TC.
