### ISSUE TITLE
Validation on code in referenced profile fails

### ISSUE THREAD

**Issue by mbaltus** [FirelyTeam/fhir-net-api#633]
If you have profiled a resource type, set a code to mandatory in it, then used that profiled type in a Reference in another profile, the validator does not work correctly in determining the slices and validating against the rules there.

I've included a zip with three profiles and an example resource, so you can see the errors.
[validation-problem.zip](https://github.com/ewoutkramer/fhir-net-api/files/2158431/validation-problem.zip)

**Comment by ArdonToonstra** [comment]
Has to do with the not implemented.resolve() discriminator.

**Comment by MatthijsvdWielen** [comment]
When validating the profiles in the .zip I now only get the error 5003: 

Exception : Internal logic failure: Cannot walk into unknown StructureDefinition with canonical 'http://www.iknl.nl/fhir/StructureDefinition/SlicingProblemObservation1_1' at 'http://www.iknl.nl/fhir/StructureDefinition/SlicingProblemObservation1#Observation.related.target'

This is a known Simplifier issue related to the .NET version 1.4 which should be solved when Simplifier moves to 1.5 or 1.6. 
The initial errors that occurred have be solved.

**Comment by ArdonToonstra** [comment]
In 1.6 the 'Cannot walk into...' is present.

![image](https://user-images.githubusercontent.com/20518398/78691471-f07a7080-78f8-11ea-974a-b8a82b88f8d7.png)

This issue is now probably better described in https://github.com/FirelyTeam/fhir-net-api/issues/1315

**Comment by ewoutkramer** [comment]
Yes, #1315 is the duplicate, but I'll close this one.

**Comment by wardweistra** [comment]
@MatthijsvdWielen This issue is now closed with the 5003 error, but are we sure the original issue (with the .resolve() descriminator) is now resolved?
