### ISSUE TITLE
Namespace for the different versions of FHIR should be unique

### ISSUE THREAD

**Issue by verzada** [FirelyTeam/fhir-net-api#673]
Use cases where this problem pops up, is when an old version of a FHIR service is exposed through the latest version of FHIR. The namespace for DSTU2 and STU3 is exactly the same, instead of having the same name as the library itself.

If the old version of the service is using DSTU2 and the new version is using STU3, the namespace is exactly the same for both of them. The issue can be solved temporarily by using alias on the dll's, but nuget will remove the alias after an update.

If the namespace is set to be exactly the same as the library, the benefit will be precise separations between versions and better reusability.

**Comment by ewoutkramer** [comment]
If I am correct, this problem turns up if you want to build software that references both versions of the API (to work against both of them), right?

We had to deal with this too, but I think @brianpos seemed to have fixed it and got nuget to work with those aliases.

I admit it would be helpful to have different namespaces, but there are some drawbacks:
* For people not using both versions concurrently in the source and upgrading their software, this would require updating all the namespaces. Though I agree this would be the least thing you'd have to do when upgrading.
* We will break compatibility on the API surface. We go into great lengths to make sure that (at least minor) version updates do not change the interface.  Changing the namespace would do this big time and everyone around the globe would have to update the namespaces. That's a major drawback.

Opinions?

**Comment by verzada** [comment]
That's correct @ewoutkramer 

DSTU2 and STU3 are in many ways two different standards when you start implementing FHIR services that incorporates both versions, because of the revisions done between the two versions. I have yet to experienced that I haven't had to to lots of revisions going from one version to another because of  f.ex. Model has no longer an entity that existed in one of the revisions, but must be mapped to or from that entity to the new entity.

I do get what you are trying to accomplish, however, the perspective from those who deploy and maintain FHIR services, do see DSTU2 and STU3 as completely different APIs. In HL7 V2 there are different namespaces for each version of V2, without that, it would be hard for f.ex create mappings from one v2 version to another for a BizTalk application because both version must be present.

Not to mention, when a DSTU2 service has been delivered from an external partner, the service stays for as a DSTU2 service for a long time. Which makes the versioning problem grow over time when someone has to implement a STU3/4 frontend service on top of that to avoid having a FHIR service with technical debt. We have several DSTU2 services which we have to expose as STU3 services because the software that is already using the DSTU2 service is not going to be changed in the near future.

**Comment by ewoutkramer** [comment]
I have not forgotten about this issue, and our ideas are still evolving.  It seems that normative resources and datatypes could now be included in an assembly carrying an unversioned namespace.  And yes, we have gotten this to work with "extern alias" support in C#.  Still, that's not trivial with the current tooling.

Having different namespaces would not make my life easier ;-)  When porting/merging changes back and forwards from dstu2/stu3/R4 I will keep getting merge conflicts or incorrect "using" statements...

**Comment by sychare** [comment]
As it's been nearly a year since the last comment here I'm interested in finding out if this was ever progressed?

I'm hitting this currently, having to need to continue to support some incoming STU3 whilst generating R4. Perhaps I'm just missing something but I'm unable to get 'extern alias' to work using NuGet in VS 2019, which makes this seemingly impossible to resolve in a sane way?

I appreciate the complexity introduced by now changing the namespaces, but I'd still push for a one-time major version bump and namespace changes across the DSTU2/STU3/R4 projects, with perhaps as mentioned a separate Normative namespace for those resources.

**Comment by brianpos** [comment]
I've been happily using 2, 3 and 4 together using the namespace aliasing. Check the fhirpathtester github project for the details as a working example.
I Definitely prefer the single namespace, and aliases for where you need multiple.
For the most part you work with one version, and upgrade occasionally.

**Comment by sychare** [comment]
@brianpos, gave fhirpathtester a whirl and had the same issues - turned out to be a ReSharper [bug](https://youtrack.jetbrains.com/issue/RSRP-476048).
Thanks for the prompt reply and suggestion, I think I've now got this working.

**Comment by ewoutkramer** [comment]
We've gotten along with extern aliases. It's not perfect, but does the job.  In the mean time are moving more and more classes (Resource, datatypes) to a common codebase as they are becoming normative.
