### ISSUE TITLE
Unjustified validation issue on multi-typed resource reference CarePlan.context

### ISSUE THREAD

**Issue by abelenthoven** [FirelyTeam/fhir-net-api#736]
Hi Ewout, all well? :)

When setting the CarePlan.context reference to an (existing) EpisodeOfCare, the validator (using the default FHIR-issued StructureDefinition for CarePlan, which is correct as far as I can see) produces the issue 'The declared type of the element (Encounter) is incompatible with that of the instance ('EpisodeOfCare')' as though it is expecting a reference to an Encounter. The specification, however, states that both Resource types (Encounter and EpisodeOfCare) are allowed

Luckily, the issue is informational by default, so it is not likely to cause any strange technical behavior

**Comment by brianpos** [comment]
Which version are you referring to stu3, dstu2 or R4?

**Comment by abelenthoven** [comment]
Hi Brian I'm using STU3

**Comment by ewoutkramer** [comment]
I will mark it as a bug for now - will review the validator in the coming weeks and make a unit-test to validate this behaviour.

**Comment by ewoutkramer** [comment]
This warning message message was indeed superfluous, fixed by #998.
