### ISSUE TITLE
Validation tool gives non-descriptive error message for errors in a slice

### ISSUE THREAD

**Issue by KatieAnne** [FirelyTeam/fhir-net-api#745]
The attached example has a fixed code value in the fragment below which does not correspond with the one in ITK-EDIS-Composition-1.mxl in the profiles/constraints folder. Rather than outputting a message stating that the code value does not correspond to the fixed code (which I have seen occurring for a non-sliced element in such a scenario), the validator outputs

[ERROR] Element does not match any slice, but the group at 'Composition.section' is closed. (at Bundle.entry[0].resource[0].section[0]).

Although this does direct the user to the correct section, it does not give as descriptive an error as it would when such an error appears outside a slice. If a section has many elements in an example, the general nature of this error could mean the user finds it difficult to locate the problem. Could a more descriptive error message be put in place for this erro?
[profiles.zip](https://github.com/ewoutkramer/fhir-net-api/files/2514601/profiles.zip)
[ITK-EDIS-Example-1-Test.zip](https://github.com/ewoutkramer/fhir-net-api/files/2514602/ITK-EDIS-Example-1-Test.zip)

**Comment by ewoutkramer** [comment]
I am working on this - will need testing and integration in 2019.2
