### ISSUE TITLE
Please add ITypedElement.NewChild(ISourceNode source)

### ISSUE THREAD

**Issue by cknaap** [FirelyTeam/fhir-net-api#790]
This allows users to add new children to an ITypedElement, reusing the type information that is already known to the parent. 

Analysis: probably by splitting up the for loop inside TypedElementNode.enumerateElements()

**Comment by ewoutkramer** [comment]
I have added such a method to a new class called ElementNode.cs, but ITypedElement remains read-only.

Take a peek here, it's still in a non-merged branch: https://github.com/FirelyTeam/fhir-net-api/blob/feature/element-node-builder/src/Hl7.Fhir.ElementModel/ElementNode.cs
