### ISSUE TITLE
ComplexTypeReader should not use ClassMapping anymore

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/fhir-net-api#799]
`ComplexTypeReader`  now uses ITypedElement as input - as it should. This means that the reader will trigger more validations done by the implemented ITypedElement (like json arrays and xhtml narratives). 

However, the `ComplexTypeReader` still uses the ClassMappings to inform how instances get created. This kind of information is also available in the ITypedElement interface, through the Definition property.

We should remove the use of ClassMappings from the ComplexTypeReader - and make sure it only uses this Definition property. 

That means we need to find the equivalent of the following properties on classmappings:

* IsPrimivite
* IsCollection
* RepresentsValueElement
* IsEnum
* SetValue/GetValue

Some of these are already available, but not all.  This probably means we need to expand the IElementDefinitionSummary interface returned by ITypedElement.Definition.

**Comment by brianpos** [comment]
Did this mean that the reflection step may not be required soon?

**Comment by ewoutkramer** [comment]
It's still there - it feeds the PocoSummaryDefinitionProvider that now adds type information into the ITypedElement.  Since the POCO parser (actually now: the xml/json parser + poco builder) now works in the ITypedElement, it shouldn't need to ALSO read the ClassMappins anymore.  

Next step would be for the PocoSummaryDefinitionProvider to not use the classMappings anymore, but instead replace them!

**Comment by brianpos** [comment]
If we code generate the pocosummaryddfinitionprovider...

**Comment by ewoutkramer** [comment]
Nice idea.... the only drawback I see is that you could not add new classes dynamically. But I haven't heard of anyone doing that....

**Comment by ewoutkramer** [comment]
In fact, the POCO builders does need a classmapping, it needs speedy access to reflection stuff to do its work, so I no longer support this notion.
