### ISSUE TITLE
FHIR Model generation for enum staring with numeric

### ISSUE THREAD

**Issue by brianpos** [FirelyTeam/fhir-net-api#804]
When the code generator for the model is outputting an enumeration it must have special rules to be able to generate a valid identifier in dotnet.
Currently this algorithm will replace any "." or "-" with a "-"
Then it will update any purely numeric values with an "N" prefix

Finally if the value starts with a digit, it will then prefix it with an "_"
(which was discussed on our call today)

This however produces a compiler warning stating that the value isn't CLS compliant.

**Comment by brianpos** [comment]
Having looked at things, can we just change this that ANY enumeration that starts with a numeric value will be changed to prefix with an "N_", and then "." or "-" will be replaced with "_"
And that's the only rule to apply?

This effects (in R4):
* AuditEvent AuditEventAgentNetworkType (N1 -> N_1 ...), AuditEventOutcome (N0 -> N_0 ...) 
* ImplementationGuide SPDXLicense (0BSD => N0BSD)
* FhirVersion (zero_01 -> N_0_01, one_0_2 -> N_1_0_2 … four_0_0 -> N_4_0_0)

**Comment by brianpos** [comment]
If we just prefix with the "N", then the AuditEvent doesn't change, as that's already employing this technique

**Comment by wmrutten** [comment]
How does the HAPI FHIR library handle this? Can we harmonize?

**Comment by ewoutkramer** [comment]
Talked to James. They use "_", so "_1_0_0" for version 1.0.0.  But I guess we'd better stay CLS compliant.

**Comment by ewoutkramer** [comment]
@brianpos - you have implemented this behaviour (with N) for R4 and later, right? Can we close the issue?

**Comment by brianpos** [comment]
Haven't committed anything yet.
Right now has _
But thinking for version, maybe specifically prefix v, and otherwise N

**Comment by ewoutkramer** [comment]
done.
