### ISSUE TITLE
FHIRPath indexOf method should return -1 if no match

### ISSUE THREAD

**Issue by wmrutten** [FirelyTeam/fhir-net-api#807]
According to the FHIR Path specification, the indexOf method should return "-1 if it is not found":
http://hl7.org/fhirpath/#string-manipulation

However the current implementation explicitly returns null:
https://github.com/ewoutkramer/fhir-net-api/blob/7d116940aa05b5031845eac8c4721962cb04c2e7/src/Hl7.FhirPath/FhirPath/Functions/StringOperators.cs#L33

```
public static ITypedElement FpIndexOf(this string me, string fragment)
{
      var result = me.IndexOf(fragment);
      if (result == -1)
          return null;
      else
          return new ConstantValue(result);
}
```

**Comment by ewoutkramer** [comment]
The fact that I explicitly coded this, means that this was de behaviour, once in pre-dstu1/normative times.

There is even a test to verify this behaviour:

```
  <test name="CSharpTest0018" inputfile="fp-test-patient.xml">
    <expression>Patient.contained.name[0].family.indexOf('qq').empty()</expression>
    <output type="boolean">true</output>
  </test>
```

(in csharp-test.xml)

**Comment by ewoutkramer** [comment]
Just double checked that in DSTU2, there are no invariants using indexOf(), so the consequences of changing it are small (for the API itself).

Shall we consider this "fixing a bug", or are we breaking existing behaviour?

**Comment by wmrutten** [comment]
So apparently the FHIR path spec itself has changed in time, and our original implementation is no longer compliant. I propose to bring the actual behavior in line with the current, final spec.
This would only break clients that rely on behavior from the draft FHIR path spec.

**Comment by Plofstoffel** [comment]
HI, I have made a [PR](https://github.com/ewoutkramer/fhir-net-api/pull/830) for this "really bite sized" issue.

**Comment by ewoutkramer** [comment]
We pulled it, thanks!
