### ISSUE TITLE
Model class SearchParamDefintion description property should be Markdown

### ISSUE THREAD

**Issue by brianpos** [FirelyTeam/fhir-net-api#811]
The search parameter field for the description was changed from a string to markdown between DSTU2 and STU3.
This should be changed in the class - as the code generation just copies the value from the markdown type into the plain string - so no indication that it's not actually a string with markdown.
(needs fixing in both STU3 and R4 - Brian Fixing in R4 already)

**Comment by ewoutkramer** [comment]
I think this is done, and we can close, right? @brianpos
