### ISSUE TITLE
FhirClient.Read<Resource>(string) - null reference when server not responding

### ISSUE THREAD

**Issue by mharthoorn** [FirelyTeam/fhir-net-api#833]
When requesting a resource with the FhirClient.Read<Resource>(string) command, a null reference error is thrown when the server does not respond. 

System.NullReferenceException
  Message=Object reference not set to an instance of an object.
  Source=Hl7.Fhir.STU3.Core
  StackTrace:
   at Hl7.Fhir.Rest.TaskExtensions.WaitResult[T](Task`1 task)

(version 1.0.0-alpha3)

**Comment by marcovisserFurore** [comment]
In the latest version of the API we get now a different exception when we perform the following Read:
```
    FhirClient client = new FhirClient("https://aidbox.io");
    var patient = client.Read<Patient>("Patient/example");
```
The exception is:
```
System.ArgumentException: Cannot determine the type of the root element at 'Resource', please supply a type argument.
Parameter name: type
```
So still not a nice response and we could return a more meaningful message.
