### ISSUE TITLE
It's time for a .NET Core 3.0 version

### ISSUE THREAD

**Issue by IvanFarkas** [FirelyTeam/fhir-net-api#840]
### It's time for a .NET Core 3.0 version
Due to the overwhelming benefits, it's time for **PURE .NET Core 3.0** version.
Based on our previous correspondence I know it's hard to leave the past behind.
At this time the advantages way outweigh the complexity of maintaining two codebases.
How can I help, please?

### [Notable Changes in 3.0.0](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0)
**My Favorites**
- Added support for ARM64 for Linux
- Added a fast in-box JSON Reader (System.Text.Json.Utf8JsonReader)
- New Range and Index types
- Support for async streams
- Added System.Buffers.SequenceReader as a reader for ReadOnlySequence
- Support for serial port APIs on Linux
- New APIs for GPIO, PWM, SPI, and I2C
- Support for TLS 1.3 and OpenSSL 1.1.1 on Linux
- Support for adding default implementations of interface members

**Other improvements**
- Windows Desktop (WPF and Windows Forms) comes to .NET Core
- WPF, Windows Forms, and WinUI are now open sourced
- Support for applications to have executables by default
- Enabled dotnet build to copy dependencies
- Support for local dotnet tools using dotnet-tools.json
- Cryptography improvements
- More BCL improvements
- Enabled tiered compilation by default for better performance
- Added assembly metadata reading with new MetadataLoadContext type

**Comment by wmrutten** [comment]
Hi @IvanFarkas, I like your enthousiasm!

I'm personally looking forward to .NET Core 3.0 as it will allow us to transition Forge (WPF application) away from .NET Framework to .NET Core. The new JSON reader will also be very useful for the API.

But we will have to maintain a NetStandard 2.0 compatible API release for a while, to keep supporting older NetFramework-based clients such as Forge. Leveraging new API's while also supporting older platforms will require #ifdef statements. We will have to be careful to keep the code base maintainable.

**Comment by brianpos** [comment]
Agree with all that's been said here, and still need to compare the new json handling with the existing to ensure that things are better.

**Comment by brianpos** [comment]
Pull requests always welcomed!
But keep in mind that we need to support all these older versions too.

**Comment by ewoutkramer** [comment]
I am looking forwards to 3.0 too! Personally, I cannot wait to switch the null-refs check on (a compiler feature), and yes, default implementations of interfaces sounds great.  I need the IoT stuff for my personal projects and C#8, and Blazor.  Yes, we are going to have 3.0 support for sure.

But it's only preview 1 currently, and if the stability of VS preview1 is any indication of the libraries' stability (not necessarily the case, I admit), the word "preview" really means "preview".   

What I don't understand is that we're not targeting specific platforms - we're targeting netstandard (1.1 and 2.x) - I am pretty sure you should be able to run the netstandard2.x libraries on .NET Core 3. 

What advantages would it bring for the API to target the .NET Core 3 platform directly?  We could start using default implementations - but I guess even the Json library will be ported for the other platforms. What am I missing?

**Comment by ewoutkramer** [comment]
But I think the easiest to get started on, if you want to help, is look at how the json parser could use the new library - I would certainly look at having an #ifdef in the parser if that speeds up parsing!

**Comment by IvanFarkas** [comment]
**Additional thoughts on why a separate codebase will be inevitable soon:**

- [Moving forward, ASP.NET Core will only run on .NET Core starting from 3.0 and ASP.NET Core will be  part of .NET Core.](https://github.com/aspnet/Announcements/issues/324)
- HTTP2, tighter security, faster JSON and other security and performance enhancements.

**Comment by ewoutkramer** [comment]
Time will tell. I am not moving yet.

**Comment by IvanFarkas** [comment]
.NET Core 3.0 is in [Preview 5](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-5/).
The API is stabilizing and the much faster JSON serializer library is added.
What speed improvements would change your mind, please @ewoutkramer?

**Comment by ewoutkramer** [comment]
The faster Json serializer would, of course ;-)

**Comment by kennethmyhra** [comment]
@ewoutkramer there are some performance tests and comparisons with System.Text.Json and Newtonsoft's Json.NET here https://github.com/dotnet/performance/pull/427. I can't find the performance test comparisons I mentioned earlier, only saw them in one of the .NET foundation JSON review videos.

System.Text.Json will be (is?) available as a package for .NET 4.6.1 and netstandard2.0 and above.

**Comment by ewoutkramer** [comment]
So, what would we have to do - we can alsways add a compile target for net core 3, but would that provide benefits over the netstandard targets?  What we *can* certainly do is implement a second json parser using the new microsoft parser, it would be just another implementation of ISourceNode (similar to implementing say an RDF parser).

What we *cannot* do (for now) I think, is start to use features that require our users to upgrade to .NET Core 3.0, or that would require us to duplicate lots of code and `#ifdef`fing them for different platforms.  
As much as I would always like to move forwards (and use c#8.0 features), we have too many users and responsibilities towards these existing users to force upgrades.

I wrote *for now*, because of course, at some point we can drop older platforms, and maybe .NET 5 is such a moment to move forwards and drop 4.0/4.5.

As we have just reached the 1M downloads mark of the library, I am painfully aware of how impactful such changes would be, but I am totally open on listening to options to upgrade without alienating a large part of our user base.

**Comment by IvanFarkas** [comment]
Well said. Move with caution.

**.NET Core 3.0** Preview 7 is [**RC**](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-7/), **[GA](https://github.com/dotnet/core/blob/master/roadmap.md)** coming next month.
**[.NET 5.0](https://github.com/dotnet/core/blob/master/roadmap.md)** is here in about a year.
The overarching wisdom from MS is that **migrate to .NET Core 3.0/3.1 and move to .NET 5.0**.
At some point, you have to have **2 separate codebase**, so everybody is super happy :-).
Your thoughts?

**Comment by kennethmyhra** [comment]
As long as the fhir-net-api library targets netstandard2.0 it will be usable by .net core 3.0 and previous versions of .net core.

I suggest focus on targeting the latest netstandard version you can without ending up with too many `#ifdef` and for legacy purposes the .net framework 4.x that is needed by users of the library that for some reason cannot upgrade.

**Comment by ivanfarkas2** [comment]
I am still trying to wrap my head around the overarching philosophy at FHIR.
Wouldn't be an advantage to please both **greenfield** **performance-centric** and very dark brownfield left behind crowd?
**Puzzled!**
