### ISSUE TITLE
Validator tries to validate Quantity looking at unit instead of code

### ISSUE THREAD

**Issue by mbaltus** [FirelyTeam/fhir-net-api#872]
When validating a Quantity with a required valueset, the validator looks at the value for unit - which contains the human readable form, instead of code - which contains the actual code from the valueset.
When they differ, the validator throws an error, because the unit is not in the required valueset.

You can test this with the ucum valueset (http://hl7.org/fhir/valueset-ucum-vitals-common.xml.html) and the example body height observation (http://hl7.org/fhir/stu3/observation-example-body-height.xml.html). This throws an error about the 'in' unit, while the '[in_i]' code is correct.

**Comment by marcovisserFurore** [comment]
I think it is correct that it throws an error when the unit is 'in', because the required valueset (http://hl7.org/fhir/ValueSet/ucum-vitals-common) does not contain a code 'in'. On the other hand the code '[in_i]' is allowed.

So the height observation example (http://hl7.org/fhir/stu3/observation-example-body-height.xml.html) is not correct I think. The valueQuantity must look like this:

```
<valueQuantity> 
    <value value="66.899999999999991"/> 
    <unit value="[in_i]"/>   <!-- CHANGE of the unit from 'in' to '[in_i]'
    <system value="http://unitsofmeasure.org"/> 
    <code value="[in_i]"/> 
  </valueQuantity> 
```

@ewoutkramer can you confirm this?

**Comment by simoneOnFhir** [comment]
IMHO, Mirjam is correct: The validator should look at valueQuantity.code not valueQuantity.unit

**Comment by ewoutkramer** [comment]
@mbaltus and @simoneOnFhir are right - I always get confused myself too (and this confusion obviously made it into hard code), but `unit` is documented to be "A human-readable form of the unit." and `code` is "A computer processable form of the unit in some unit representation system", so we should check code, `unit` is irrelevant and could contain whatever is human readable.

**Comment by ewoutkramer** [comment]
I am just wondering now why I would have a special case for Quantity, it's validated by a StructureDefinition like any other thing.

**Comment by ewoutkramer** [comment]
Found it, in PocoBuilderExtensions.cs, line 114:

``` csharp
     Coding parseQuantity(ITypedElement nav)
     {
                var newCoding = new Coding();
                var q = instance.ParseQuantity();
                newCoding.Code = q.Unit;
                newCoding.System = q.System ?? "http://unitsofmeasure.org";
                return newCoding;
     }
```

We derive a bindable Coding from a Quantity, and here newCoding.Code is set to q.Unit instead of q.Code.
