### ISSUE TITLE
DirectorySource.LoadArtifactByName should handle duplicate file names

### ISSUE THREAD

**Issue by wmrutten** [FirelyTeam/fhir-net-api#875]
`DirectorySource.LoadArtifactByName` expects a filename, or a relative file path (relative to the content directory). The implementation scans the summaries to find a single unique match for the specified filename.

The current implementation uses the LINQ `SingleOrDefault` method, which throws an exception when the content directory contains multiple files with the same file name (in different subfolders).

Proposal: try to return the "best/nearest" match, if unambiguous.

Example:
```
\Project\Patient.xml
\Project\Examples\Patient.xml
\Project\Examples\Old\Patient.xml

source.LoadByArtifactName("Patient.xml") => match \Project\Patient.xml
source.LoadByArtifactName("Examples\Patient.xml") => match \Project\Examples\Patient.xml
source.LoadByArtifactName("Examples\Old\Patient.xml") => match \Project\Examples\Old\Patient.xml
source.LoadByArtifactName("Old\Patient.xml") => match \Project\Examples\Old\Patient.xml
source.LoadByArtifactName("Profiles\Patient.xml") => no match
```

**Comment by wmrutten** [comment]
Here is a utility method I'm currently using in Forge.
The `relativePath` argument expects a filename or a path relative to the content directory.
The method tries to select the best match (shortest relative path to the content directory).

```
static Stream LoadArtifactByNameSafe(this DirectorySource source, string relativePath)
{
	bool isCandidateArtifact(ArtifactSummary summary)
		=> !(summary is null)
		&& !summary.IsFaulted
		&& !(summary.Origin is null)
		&& summary.Origin.EndsWith(Path.DirectorySeparatorChar + relativePath, FileUtils.PathComparison);

	var candidates = source.ListSummaries().Where(isCandidateArtifact);

	// We might match multiple files; pick best/nearest fit
	ArtifactSummary match = null;
	foreach (var candidate in candidates)
	{
		if (match is null || candidate.Origin.Length < match.Origin.Length)
		{
			match = candidate;
		}
	}
	return match?.Origin is null ? null : File.OpenRead(match.Origin);
}
```

**Comment by ewoutkramer** [comment]
I've seen the code - this changes the original logic rather drastically - since originally the name of your file should have been unique.  Does it make sense to return without error if there's > 1 hit?
