### ISSUE TITLE
StructureDefinitions unable to resolve reference to profile (STU3 and R4)

### ISSUE THREAD

**Issue by toclean** [FirelyTeam/fhir-net-api#882]
[ERROR] Unable to resolve reference to profile 'http://hl7.org/fhir/StructureDefinition/Bundle' (at Bundle)

Currently all unit test are failing on STU3 due to this error. Nothing has changed and the zip is still present in the directory. Only thing I can think of is that the URL maybe changed with the new website for R4?

**Comment by ewoutkramer** [comment]
Hi @toclean, what do you mean, "all unit tests are failing"?  Do you mean the ones in the current master branches?  Which version have you checked out?  They all run fine on our CI build, so I suspect it is something local to your machine.

**Comment by toclean** [comment]
Sorry here is some context. I have created an api that uses the FHIR validator and as of around the start of the new year all endpoints utilizing the FHIR validator fail. Note these endpoints are something that I have created on my local.

**Comment by ewoutkramer** [comment]
Ok, thanks!  Do you remember updating the .NET (validator) API?

**Comment by toclean** [comment]
# Current Versions
Hl7.Fhir.Specifications.STU3    v0.93.4
Hl7.Fhir.STU3                           v0.93.4
Hl7.Fhir.Support                       v0.4.2
Hl7.FhirPath                              v0.4.2

I have not updated the validator API. I have tried moving everything to R4 but with no success.

**Comment by ewoutkramer** [comment]
Ok, so these are (very) old versions of the API -> nothing should have changed there.  As far as I know, we have no dependency on external servers - except for terminology validation.  So, it might well be that the terminology endpoints that I use have changed.  Maybe @mbaltus can dig deeper if you can show us your start-up code for the validator?

**Comment by ewoutkramer** [comment]
No more feedback, closing issue.
