### ISSUE TITLE
Zipsource is not handling files in subdirectories

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/fhir-net-api#883]
When you use ZipSource , for example to extract summaries, then it will not traverse subdirectories. Even by forcing it in the settings, it will not handle files in subdirectories. 

So 
```
var zip = new ZipSource(@"some.zip", new DirectorySourceSettings() { IncludeSubDirectories = true });
zip.ListSummaries();
```
will not list the summaries of files in the subfolders of the zipfile.

**Comment by ewoutkramer** [comment]
Fixed by #902
