### ISSUE TITLE
[Validator] Validator gives incorrect instance count error for sliced elements

### ISSUE THREAD

**Issue by ArdonToonstra** [FirelyTeam/fhir-net-api#885]
Validator incorrectly gives errors for instance counts. Below are two scenarios.

Issue from Nictiz example 
----------------------------

Have a look at the files named Testset 1

![testset 1 - 2019-02-26 14_42_32-window](https://user-images.githubusercontent.com/20518398/53417151-3ca87100-39d5-11e9-925d-714c90e70c21.png)

Issue from other users on Simplifier:
-----------------------------------

Date: 2/11/2019 10:21:25 PM +00:00

If you validate this Example you get an error: "Invalid : Instance count for 'HumanName.family.extension:namenszusatz' is 3, which is not within the specified cardinality of 0..1"
The Extension is actually only used once, i could validate with no issues with hapi/java validator.

Example:
https://simplifier.net/basisprofilde/example-patient-de-basis-humanname-komplex

Profile:
https://simplifier.net/basisprofilde/patient-de-basis-0.2
https://simplifier.net/BasisprofilDE/humanname-de-basis-0.2

Have a look at the files named Testset 2.

**Comment by ArdonToonstra** [comment]
[Validator.zip](https://github.com/ewoutkramer/fhir-net-api/files/2905746/Validator.zip)

**Comment by furoreSebastiaan** [comment]
https://simplifier.net/grunndata-r4/patient-example

Is having the same issue as 

https://simplifier.net/basisprofilde/example-patient-de-basis-humanname-komplex

**Comment by ArdonToonstra** [comment]
I believe this may be about two different issues. My own example has a different discriminator slicing than the issue report by BaisProfile, where it is about multiple extension slices.

My own example may be related to this chat: https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Slicing.20and.20value.20sets

**Comment by dnperfors** [comment]
Do you have any idea when this will be picked up? We have the same issue.

**Comment by ewoutkramer** [comment]
There's now a preview of 1.4-alpha available to test the new code!  Of course, you can also build it yourself from the /1.x/ branches in the project.

**Comment by ArdonToonstra** [comment]
@furoreSebastiaan , I can't reproduce the errors of the German profiles as well. 

The Nictiz issue was related to #1070 and is continued in #1147

Therefore I believe we can close this issue.
