### ISSUE TITLE
Additional rules will get confused by hybrid typed trees

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/fhir-net-api#889]
The AdditionalStructuralRule annotation is checked by the TypedElement class (maybe called TypedElementOnSourceNode by the time you read this) to retrieve additional validation rules from lower-level parsers (like the xml/json parsers) to run when type information becomes available.  Examples are checking for element order (XML specific), checking for the use of JSON Arrays for repeating elements, etc.  

These rules cannot be enforced by the lower-level parsers, since they don't yet have type information, hence they are being run by the TypedElement class by querying the nodes for the AdditionalStructuralRule. There is a problem however when we construct SourceNode trees in which only part of nodes comes from, say, the FhirXmlNode and other nodes have been constructed by hand or imported from a json presentation.  

In this case, when the TypedElement queries for the additional rules, it will subsequently run these rules on *all* children.  This means that a parent node coming from Xml, with added children from another representation, will still be validated against rules meant for xml sources: a validator that checks the order of elements will be run on all children of an Xml-based node.

Of course, this will result in spurious or incorrect validation errors.  It's not completely obvious what the desired behaviour is, though one solution may be for the additional validation rule to double check what the source of the validated nodes is, as to avoid running format-specific rules on the wrong kind of node.

**Comment by cknaap** [comment]
I believe this is not completely fixed. I added a unittest to prove it in branch fix/hybridTreeOrder.

**Comment by cknaap** [comment]
Sorry, my bad. User error with git...
But the unittest in the branch may still be of value to prove it was fixed.
