### ISSUE TITLE
DirectorySource should expand specified contentDirectory to full path

### ISSUE THREAD

**Issue by wmrutten** [FirelyTeam/fhir-net-api#894]
The `FilePatternFilter` implementation logic assumes that the base directory is a full path specification, otherwise the specified filters will not match any files.

Proposal: the `DirectorySource` constructor should always expand the specified `contentDirectory` folder path to a full (absolute) path specification.

**Comment by ewoutkramer** [comment]
I guess that is true ;-)

**Comment by ewoutkramer** [comment]
Fixed by #895.
