### ISSUE TITLE
ElementDefinitionSerializationInfo.IsRequired is wrong

### ISSUE THREAD

**Issue by cknaap** [FirelyTeam/fhir-net-api#896]
It checks for minimum cardinality > 1.

Should be >= 1.

Result for me is that MaskingNodeSettings.IncludeMandatory has no effect.

**Comment by wmrutten** [comment]
Does this imply that serialization is currently broken?

**Comment by ewoutkramer** [comment]
Ouch.

@wmrutten, no, not the main serialization at least.

I looked at what parts of our codebase use IsRequired, and it turns out that's just the MaskingNode.  So, as @cknaap pointed out, that results in broken _summary serialization.

**Comment by ewoutkramer** [comment]
Fixed by #909
