### ISSUE TITLE
Make sure we only build the minimum number of targetplatfoms in DEBUG

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/fhir-net-api#899]

**Comment by wmrutten** [comment]
I noticed that Hl7.Fhir.Core takes a relatively long time to build, introducing annoying delays when fixing bugs and re-running unit tests. Would be nice if we could manage to speed this up a bit.

**Comment by ewoutkramer** [comment]
I tried this with a conditional DEBUG, but alas the build server (actually: the `dotnet build` toolchain) does not support making platforms conditional.

There is now a script `build\ChangeTargetFrameworks.ps1` that will let you (locally) update the .csproj files to use only a single platform.
