### ISSUE TITLE
ArtifactSummary should indicate Bundle entries

### ISSUE THREAD

**Issue by wmrutten** [FirelyTeam/fhir-net-api#904]
The `ArtifactSummaryGenerator` class transparently extracts summaries from `Bundle` entries. However currently clients cannot detect if a returned `ArtifactSummary` represents a `Bundle` entry or a stand-alone resource file. The `ArtifactSummary` class should expose a property that indicates if the described resources represents a `Bundle` entry.

**Comment by ewoutkramer** [comment]
Fixed by #905.
