### ISSUE TITLE
Transaction failure doesn't return null

### ISSUE THREAD

**Issue by yoliva** [FirelyTeam/fhir-net-api#907]
I'm making a transaction using the client. If I make a transaction and it fails I get an exception instead of `null` as the transaction method stands:

```
A bundle as returned by the server after it has processed the transaction, or null if an error occurred
```

**Comment by ewoutkramer** [comment]
Getting an exception is actually the right behaviour (that's what all the other calls on the client do to), it's the documentation that is wrong ;-)

**Comment by ewoutkramer** [comment]
Fixed by #907.

**Comment by yoliva** [comment]
why raise an exception instead of return the error returned for the server? if we got an exception on every call we may end by having `try-catch` blocks all over the code.

**Comment by brianpos** [comment]
The outcome from the server is in the exception. And in many cases the return type of the fhir call is a specific resource type, so doesnt need casting.
Searches return Bundle, Generic Get<Patient>(...) returns a Patient.
So not having the try catch for the error cases would be replaced with casting and type checking instead.
