### ISSUE TITLE
NavigatorStreamFactory throws lots of exceptions for unknown files

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/fhir-net-api#913]
These lines:

``` csharp
            if (ThrowOnUnsupportedFormat)
            {
                throw Error.NotSupported($"Unsupported file format ('{path}').");
            }
```

throw lots of Exceptions in directories with non json/xml files.  Often these are then simply caught by the ArtifactSummaryGenerator.cs (used in the resolvers): 

``` csharp
            catch (Exception ex)
            {
                result = new List<ArtifactSummary>
                {
                    ArtifactSummary.FromException(ex, filePath)
                };
            }
```

I can see hundreds of these exceptions caught - can we improve on this design? @wmrutten ?

**Comment by wmrutten** [comment]
Note that this behavior is configurable via property `ThrowOnUnsupportedFormat`. Disable this property if you don't need the exception information.

Alternatively, we could implement a separate dummy `INavigatorStream` implementation for unrecognized/unsupported file extensions, where method `INavigatorStream.MoveNext` always returns false and `INavigatorStream.Current` always returns `null`. The `INavigatorStream.Position` property can still return the file name to the client (e.g. `ArtifactSummaryGenerator`) to allow futher procession.

**Comment by wmrutten** [comment]
Fixed by #952

**Comment by ewoutkramer** [comment]
I am glad we've fixed this. This change was very painful for tools using the DirectorySource as a validation source.  E.g. the Windows validation tool that I wrote had an initial start-up time (to scan the specification.zip) of bout 4 seconds in version 1.1 of the API.  In version 1.2 this had become 12 seconds.

We'll have to double-check that the 1.3 release fixes this.

**Comment by ewoutkramer** [comment]
I just checked the latest 1.3 alpha - the issue seems to be fixed, thanks.
