### ISSUE TITLE
There is no EVENT class ??

### ISSUE THREAD

**Issue by one0410** [FirelyTeam/fhir-net-api#916]
Hello,

https://www.hl7.org/fhir/event.html
I found that there is no EVENT class that is defined in above document.
Or I miss something?

Andy

**Comment by ewoutkramer** [comment]
Hi Andy,

No, the Event class is abstract, it's a pattern or guideline that is followed by the designers of FHIR who create the real resources, therefore these pattern classes (there are also Request and Definition patterns) do not have a representation in .NET.
