### ISSUE TITLE
Composition does not contain the "Focus" field Fhir.R4 

### ISSUE THREAD

**Issue by sacha-br** [FirelyTeam/fhir-net-api#918]
I am using nuget Hl7.Fhir.R4 0.96.1
http://hl7.org/fhir/R4/composition-definitions.html#Composition.section.focus

**Comment by mbaltus** [comment]
Hi!
This has been fixed as of version 1.2.0-beta1. You can install that package if you select 'show pre-release packages' in the NuGet package manager.

**Comment by ewoutkramer** [comment]
We are probably publishing the final version today!
