### ISSUE TITLE
Missing release notes

### ISSUE THREAD

**Issue by kjellegafvelin** [FirelyTeam/fhir-net-api#927]
It would be great if each release had some release notes. It would be significally easier to make a judgement about whether you would need to update to a new version or not.

**Comment by ewoutkramer** [comment]
Hi Kjell, we actually DO have release notes, but I guess they are not as easy to find as I would like to: it's here with the [rest of the documentation](http://docs.simplifier.net/fhirnetapi/releasenotes.html).

I think I'll start out by having a link to these on the Github repo.  Do you have suggestions to increase the visibility?

**Comment by kjellegafvelin** [comment]
I think that would be excellent! I also didn't notice that you had a link to the release notes on the Nuget page. My bad...

If you add a link on the Release page it would be great if it pointed to the actual release notes section for that particular release. Just like this [Link to Release Notes](http://docs.simplifier.net/fhirnetapi/releasenotes.html#beta1-dstu2-stu3-r4-released-20190220). I noticed that there are ID's for each section on that page.

**Comment by marcovisserFurore** [comment]
Ho Kjell,

For the new version (1.2.0) we added the release notes also the release page of GitHub (https://github.com/FirelyTeam/fhir-net-api/releases). For future releases we will update this page.

So thank you for your suggestion.
