### ISSUE TITLE
Settings should be used by the parameter rather than the base property

### ISSUE THREAD

**Issue by brianpos** [FirelyTeam/fhir-net-api#941]
https://github.com/FirelyTeam/fhir-net-api/blob/dfaf0f9000d42c82cc8c15ad91496e7d41063a08/src/Hl7.Fhir.Core/Serialization/FhirXmlParser.cs#L27

**Comment by ewoutkramer** [comment]
Hi @brianpos, I am not sure what you mean here?

**Comment by marcovisserFurore** [comment]
The parameter `settings` is not used here. It is using Settings of the base class instead, which is not good.

**Comment by ewoutkramer** [comment]
This is actually also wrong in FhirJsonParser

**Comment by ewoutkramer** [comment]
Fixed by #977.
