### ISSUE TITLE
Update ModelInfo.cs to R4

### ISSUE THREAD

**Issue by wmrutten** [FirelyTeam/fhir-net-api#943]
* `IsConformanceResource()` - also support `GraphDefinition` and `TerminologyCapabilities`
* `IsProfiledQuantity()` - also support `MoneyQuantity`
* `IsInstanceTypeFor()` - also support Uri subtypes

**Comment by ewoutkramer** [comment]
I think the IsInstanceTypeFor() is wrong - there are no Uri subtypes, see here: http://hl7.org/fhir/datatypes.html#primitive

"Although the url and canonical are specializations of uri, they are never substituted for each other"

**Comment by ewoutkramer** [comment]
Unfortunately, this change has been applied as part of #951 - we might have to undo it when the gForge issue is resolved.

**Comment by ewoutkramer** [comment]
The response to our gForge issue is in: https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=20853&start=0

This makes clear there is *no* substitution between datatypes, will have to adapt IsInstanceTypeFor() accordingly.
