### ISSUE TITLE
DirectorySource.Summaries - ignore unknown file extensions

### ISSUE THREAD

**Issue by wmrutten** [FirelyTeam/fhir-net-api#952]
The `DirectorySource.Summaries` member may currently trigger runtime exceptions when encountering unrecognized files in the content directory (e.g. XML schemas). Although the `DirectorySource` class handles these exceptions, they cause considerable overhead / performance degradation.

Currently, the `ArtifactSummaryGenerator` always creates a DefaultNavigatorStreamFactory instance with ThrowOnUnsupportedFormat = true.

Instead, the `DirectorySource` class should inject a ConfigurableNavigatorStreamFactory into the `ArtifactSummaryGenerator` class with ThrowOnUnsupportedFormat = false.

**Comment by ewoutkramer** [comment]
I guess this is going to be handled by PR #952?

**Comment by wmrutten** [comment]
Solved by pull request #985 for develop-stu3
Note: original pull request #954 is broken and obsolete.
