### ISSUE TITLE
Interface broken after  PR #931

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/fhir-net-api#955]
In PR #931 3 public fields of Hl7.Fhir.Support.Issue made readonly. With this action we broke the interface, because users cannot set these fields anymore. 

These fields should be writable again:
* public OperationOutcome.IssueType Type
* public OperationOutcome.IssueSeverity Severity
* public int Code

**Comment by ewoutkramer** [comment]
Ah, these were the suggestions done by Visual Studio - obviously it does not detect use of these properties by code outside our own codebase ;-)
