### ISSUE TITLE
Include collectedDateTime in specimen

### ISSUE THREAD

**Issue by yoliva** [FirelyTeam/fhir-net-api#963]
I'm trying to set the `collectedDateTime` for `Specimen` resources but looks like the nuget only has a `.Collected` field instead of `collectedDateTime` and `timePeriod`. If that was a decision by design how would you recommend to use this?

**Comment by brianpos** [comment]
For properties where the type could be one or other this is the style, and you cast when required. 
Speciman.collected = new FhirDateTime(...)
Or
Speciman.collected = new Period(...)
