### ISSUE TITLE
SnapshotGenerator - type.(target)profile should replace base, not merge

### ISSUE THREAD

**Issue by wmrutten** [FirelyTeam/fhir-net-api#965]
ElementDefinition.type.(target)profile elements need custom merging behavior:
- Use the differential profiles if the list is not empty
- Otherwise inherit the snapshot profile list
- Do NOT merge differential & snapshot collections; this would prevent derived profiles from constraining the list of (target) profiles.

**Comment by ewoutkramer** [comment]
PR #966 is a fix for this.
