### ISSUE TITLE
Rename specification.zip to specicification.r4.zip

### ISSUE THREAD

**Issue by brianpos** [FirelyTeam/fhir-net-api#967]
When an application has more than 1 version of the FHIR specification loaded need to be able to have both files, so rename so they won't clash

**Comment by marcovisserFurore** [comment]
We had the same problem in Vonk. I managed to came up with the following solution in the cs-project file:

```
  <ItemGroup>
    <PackageReference Include="Hl7.Fhir.Specification.R3" Version="1.2.1" GeneratePathProperty="true" ExcludeAssets="contentFiles" />
    <PackageReference Include="Hl7.Fhir.Specification.R4" Version="1.2.1" GeneratePathProperty="true" ExcludeAssets="contentFiles" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="$(PkgHl7_Fhir_Specification_R3)\contentFiles\any\any\specification.zip">
      <Link>specification_R3.zip</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="$(PkgHl7_Fhir_Specification_R4)\contentFiles\any\any\specification.zip">
      <Link>specification_R4.zip</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
```

which will produce 2 specification files: `specification_R3.zip` and `specification_R4.zip`

Maybe you can use this as well?

**Comment by brianpos** [comment]
Sounds good, I'll give it a try.

**Comment by ewoutkramer** [comment]
Nice trick.  I guess renaming wouldn't hurt - it's in line with what we have decided to do with the upcoming HL7 FHIR packages (at least, in npm) - the major version nr will become part of the id/name of the package.

**Comment by ewoutkramer** [comment]
will fix this when we start to use packages.
