### ISSUE TITLE
Custom Resource Serialization with FhirJsonSerializer

### ISSUE THREAD

**Issue by tresoldigiorgio** [FirelyTeam/fhir-net-api#973]
I've (re)create the ItemInstance resource in my project after the elimination in R4 but i'm unable to use the FhirJsonSerializer (or FhirXmlSerializer) to serialize data in my fhir server search.
I've copied the class from old source here https://github.com/FirelyTeam/fhir-net-api/blob/0.95.0-r4/src/Hl7.Fhir.Core/Model/Generated/ItemInstance.cs

the code for serialization are
`
var writer = new StreamWriter(response.Body);
var jsonwriter = SerializationUtil.CreateJsonTextWriter(writer);
var fhirJsonSerializer = new FhirJsonSerializer();
fhirJsonSerializer.Serialize(resource, jsonwriter, st);
var st = SummaryType.False;
`

and the output are
`
{
  "resourceType": "Bundle",
  "id": "53286955-4357-4c07-bde6-48119af24d16",
  "meta": {
    "lastUpdated": "2019-05-14T10:44:49.3055354+02:00"
  },
  "type": "searchset",
  "total": 1,
  "entry": [
    {
      "fullUrl": "http://localhost:7001/fhir/ItemInstance/39ea0955-01ad-481c-8829-2124d69d68c5",
      "resource": {
        "resourceType": "ItemInstance",
        "id": "39ea0955-01ad-481c-8829-2124d69d68c5",
        "meta": {
          "versionId": "1",
          "lastUpdated": "2019-05-13T13:10:04.164+00:00"
        }
      }
    }
  ]
}
`

I've read the source code and i found that the fields are taken from "NamedChildren" property of the resource class but i'm unable to override that property because is internal! 

There is a solution for me? :-D

thanks

**Comment by ewoutkramer** [comment]
Hi @tresoldigiorgio - yes, I think you are right. You are supposed to be able to create your own classes this way, but you might be right that overriding NamedChildren is not possible since it is internal. 

If you are to change the source of the API, you can ofcourse just copy & paste the old file, but it is probably better to copy the StructureDefinition for this resource from the STU3 branch over to the R4 branch.  These are in Model/Source/profiles-resources.xml.   The classes are generated from these files.  You can then look for the .tt files in the project and run the generators again to generate the new class.

Apart from that, I need to think about making that NamedChildren function public.....

**Comment by ewoutkramer** [comment]
Ok, made this public. But I think this is actually quite a burden on the developer - especially because we now have both  "Children" and "NamedChildren", which are basically the same.  We could remove `Children` and have just `NamedChildren` instead, since that's a superset.

**Comment by ewoutkramer** [comment]
These functions are there just for performance reasons - it's much quicker to list the children this way than to use reflection to get to them.  I am thinking about making this optional, so have an interface (say `IChildrenProvider`) that POCOs _may_ implement.  If they do - we'll use that, if they don't, we'll just use (slower) reflection.

**Comment by brianpos** [comment]
Yes, these are for performance so you don't have to iterate and go direct to property required while evaluating things like fhirpath.

**Comment by gstoian** [comment]
NamedChildren property has been made public when we started the process of separating the version specific code from the one that is common between versions. This should solve the initial request.

> We could remove Children and have just NamedChildren instead, since that's a superset.

As this is another topic of discussion I think we should create another item for it.
