### ISSUE TITLE
Validation of slicing on pattern is not supported

### ISSUE THREAD

**Issue by pieter-edelman-nictiz** [FirelyTeam/fhir-net-api#975]
I made a profile on Observation (STU3) with a slicing on .component, discriminated by pattern/code. 

When I try to [validate an instance against this profile on Simplifier](https://simplifier.net/test20171158/observation-example/$validate), it gives me the error message: NotSupported : Slicing with a discriminator of type 'Pattern' is not yet supported by this validator.

Well ... we would like to have this feature supported.

**Comment by ewoutkramer** [comment]
Hi Pieter, this is pretty high on our own wishlist too, and we will probably add this facility this summer!

**Comment by brianpos** [comment]
I thought this actually worked... When I did that work fixing some stuff a while back.

**Comment by ewoutkramer** [comment]
@brianpos, you are right, our validator does already support it. It's just that my if() determining support for it was incorrect. I think your PR #995 fixes this.

**Comment by brianpos** [comment]
Yup.

**Comment by pieter-edelman-nictiz** [comment]
Awesome work, guys!
