### ISSUE TITLE
StructureDefinitionSummaryProvider does not handle all magic primitives

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/fhir-net-api#984]
[Only applies to R4]

The function `buildTypes(ElementDefinitionNavigator nav)` has special cases for handling the "terminal" elements (.value, Extension.url, Element.id).

However, it does not actually handle Element.id.  The reason we have not found this issue yet is that, by coincidence, the generated core StructureDefinitions for the datatypes (which have Element.id) are wrong.  Instead of leaving the Type.Code out and having an extension with the primitive type (see for example Element.id in profiles-types.xml), any derived profile (take BackboneElement) will incorrectly have its .id Type set to "string".

This is the reason our unit-test TestSpecialTypes that verifies this behaviour succeeds.  Once this issue gets reported and fixed by HL7 however, `buildTypes` will fail.

I think we should fix this before this happens, by either adding another special case, or by actually checking for the presence of these "compiler magic" extensions (e.g. http://hl7.org/fhir/StructureDefinition/structuredefinition-json-type)

**Comment by wmrutten** [comment]
Clarification: the official core `StructureDefinition` resources from the FHIR spec (profiles-types/profiles-resources) are incorrect; more specifically, the generated snapshot components are not 100% compliant, due to bugs in the official snapshot generator that is part of the FHIR build tool. This bug effects all [...].id child elements, as described in the issue above.
Snapshots that are (re-)generated by the .NET Snapshot Generator do not suffer from this issue.

**Comment by marcovisserFurore** [comment]
Related to #1145

**Comment by ewoutkramer** [comment]
For STU3:

```csharp
   // Narrative.div
   var div = provider.Provide("Narrative");
   checkType(div, "div", false, "xhtml");
   checkType(div, "id", false, "string");

   // Element.id
   var elem = provider.Provide("Element");
   checkType(elem, "id", false, "string");

   // Extension.url
   var ext = provider.Provide("Extension");
   checkType(ext, "url", false, "uri");
```

**Comment by ewoutkramer** [comment]
For R4:

```csharp
  // Element.id
  var elem = provider.Provide("Element");
  checkType(elem, "id", false, "string");

  // xhtml.id
  var xhtml = provider.Provide("xhtml");
  checkType(xhtml, "id", false, "string");

  // Narrative.div
  var div = provider.Provide("Narrative");
  checkType(div, "div", false, "xhtml");
  checkType(div, "id", false, "string");  // also try `id` in a derived element

  // Extension.url
  var ext = provider.Provide("Extension");
  checkType(ext, "url", false, "uri");

  // Resource.id
  var res = provider.Provide("Resource");
  checkType(res, "id", false, "id");

  // Patient.id - derived type
  res = provider.Provide("Patient");
  checkType(res, "id", false, "id");
```
