### ISSUE TITLE
FhirXmlNode.Parse() does not raise an error when attribute is empty

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/fhir-net-api#988]
The following xml should raise an error during `FhirXmlNode.Parse()`, because code consists only of 1 space (whitespace), which is not allowed ("Attributes cannot be empty. Either they are absent, or they are present with at least one character of non-whitespace content")

```
<CodeSystem>
   <status value = "active"/>
   <content value = "complete"/>
   <concept>
      <code value = " "/>
      <display value = "Empty code"/>
   </concept>
</CodeSystem>
``` 

`FhirJsonNode.Parse()` will throw an error when `PermissiveParsing` is false. This behavior should be the same for `FhirXmlNode.Parse()`

**Comment by gstoian** [comment]
hey Marco, I tested your case with both FhirJsonNode and FhirXmlNode and they both raised errors on the value for "code". This is what I have from FhirXmlNode:

`System.FormatException: Parser: The attribute 'value' in element 'code' has an empty value, which is not allowed. (at line 5, 11)`

Though you will not see the error at `FhirXmlNode.Parse()` as it is a lazy process, it will appear when you actually need to do something with ISourceNode resulted from parsing the xml.

**Comment by ewoutkramer** [comment]
No response from Marco, closing.
