### ISSUE TITLE
Fhirpath Invariants should report which structure definition and key caused it

### ISSUE THREAD

**Issue by brianpos** [FirelyTeam/fhir-net-api#992]
In order to more effectively locate the source of an issue, the invariant from the structure definition should be included to be able to track the source of the message

**Comment by brianpos** [comment]
And should be able to permit external apps use the Hl7.Fhir.Support.Issue.Create should be public so that other systems can use it to create error messages too.

**Comment by ewoutkramer** [comment]
Fixed by #995.
