### ISSUE TITLE
Binding validation erroneously reporting an issue with the instance.

### ISSUE THREAD

**Issue by brianpos** [FirelyTeam/fhir-net-api#993]
https://github.com/FirelyTeam/fhir-net-api/blob/a9f29dd5223f0d9efd9f41fc504ef71f70211ed2/src/Hl7.Fhir.Specification/Schema/Binding.cs#L79-L83

This code should not be reporting an issue here, this is normal operation in a questionnaire response answer which can have multiple types value[x], including a coding, so the binding here is only relevant when the answer type is a coding.
And there should be other validation rules that capture that the appropriate type is found.
Hence this Issue should not be created, it should be permitted to continue.

If anything, its an error on the StructureDefinition, not the instance that you're validating against it.

**Comment by ewoutkramer** [comment]
Fixed by #1023.
