### ISSUE TITLE
.NET Client async issue

### ISSUE THREAD

**Issue by andreifmc** [FirelyTeam/fhir-net-api#997]
Hello everyone,

During a round of profiling, we discovered a potential issue in the .NET client library. A call to the SearchAsync method will eventually block:

![image](https://user-images.githubusercontent.com/51225205/58685924-fbce4880-8385-11e9-8194-d7893fd87c95.png)

The part that is causing the wait is in WebRequestExtensions.cs:

```
return t.ContinueWith(parent =>
{
	if (parent.IsFaulted)
	{
		if (parent.Exception.GetBaseException() is WebException wex)
		{
			if (!(wex.Response is HttpWebResponse resp))
				throw t.Exception.GetBaseException();
			return resp;
		}
		throw t.Exception.GetBaseException();
	}
	return parent.Result;
});
```

The problem is caused by that .Result which is equivalent to Task.Wait

Rewriting it like this should eliminate that wait:

```
return t.ContinueWith(async parent =>
{
	if (parent.IsFaulted)
	{
		if (parent.Exception.GetBaseException() is WebException wex)
		{
			if (!(wex.Response is HttpWebResponse resp))
				throw t.Exception.GetBaseException();
			return resp;
		}
		throw t.Exception.GetBaseException();
	}
	return await parent;
}).Unwrap();
```

I think this fix is definitely worth doing.

What do you guys think?

**Comment by ewoutkramer** [comment]
Hi Andrei, to be perfectly honest, I myself know almost nothing about async - I have had a few PRs with small changes to exactly this bit of code, improving it step by step.   If you have found this to solve the problem, with no side-effects I am OK to pull it. 

Just pinging @brianpos and @mharthoorn.  Maybe @brendankowitz ?

**Comment by mharthoorn** [comment]
Agreed that this is not a place to block a task with a synchronous wait for .Result.
So yes.

**Comment by brendankowitz** [comment]
Perhaps the entire `GetResponseAsync` could be cleaned up to just use async/await pattern. There is also a .Result and .Wait in the NETSTANDARD1_1 portion too

**Comment by ewoutkramer** [comment]
@andreifmc - is that something you might want to do for us?

**Comment by andreifmc** [comment]
@ewoutkramer I will take a look at this next week, should I branch from develop-stu3?

**Comment by ewoutkramer** [comment]
Yes, please!

**Comment by andreifmc** [comment]
After doing some more profiling and it turns out that trace I showed above was taken using an older version (1.1.3) that doesn't have this fix in it: [https://github.com/FirelyTeam/fhir-net-api/pull/897](url). The trace actually shows that Wait that was removed with the fix.

The latest code seems fine after all, that .Result is executed after the initial task completed, so it will not block anything.

I believe this issue can be safely closed

**Comment by ewoutkramer** [comment]
Thanks for the effort, all!

**Comment by jhudsoncedaron** [comment]
For the next guy who comes across this; the problem isn't calling `Task<T>.Result` inside `.ContinueWith()`. Calling `Task<T>.Result` inside `.ContinueWith()` does not block (in fact that's the intended use case). The problem was higher up the call stack.
